### ISSUE TITLE
Hero sections are broken

### ISSUE THREAD

**Issue by kronnox** [aemsites/stericycle-shared#106]
Some of the recent changes merged into main broke the hero sections. On the landing-page the hero is missing the background image on other pages the text isn't centered anymore.

**Comment by jindaliiita** [comment]
Might be related to https://github.com/aemsites/stericycle-shared/pull/96/commits/4679adb3b9ec2568f5a2c43458a3d8768f171bf0
@MarquiseRosier Can you please check this.

**Comment by jindaliiita** [comment]
@bstopp , assigning this to you since you're already working on hero block changes. I believe this will be addressed alongside the other issues you're working on. So, feel free to close this
