### ISSUE TITLE
Blog QA Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#114]
We have completed first found of QA for Blogs. See issues below.

- Internal links do not appear to be resolving – result in a 404 error (fix 404s)
    - Several examples on - https://main--shredit--stericycle.aem.live/en-us/blog/10-most-dangerous-ways-to-dispose-of-hard-drives

Related Content

- Related Content  section doesn’t appear to be working on all pages
    - Example - https://main--shredit--stericycle.aem.live/en-us/blog/you-wont-believe-where-some-companies-go-wrong
- Sidebar loads oddly slow. Looks to be deliberate to enhance site speed. Anything we can do to improve this?

Design Issues

- Not all Hyperlinks are underlined – seems some randomly are and some are not Example: https://main--shredit--stericycle.aem.live/en-us/blog/10-reasons-why-all-businesses-need-safeguards
- Parent breadcrumb just says “Blog” vs “Document & Information Destruction Tips & How-To's” on the live site. Assume this may just be based on the meta title of the parent page?

Issue List:
- [ ] fix 404s
- [ ] Enhance related content block #116 
- [ ] fix underline links

**Comment by jindaliiita** [comment]
Closing this issue since all issues listed here are resolved and created one follow up issue for the sidebar
https://github.com/aemsites/stericycle-shared/issues/357
