### ISSUE TITLE
Caching to local storage for the query-index lookups

### ISSUE THREAD

**Issue by kronnox** [aemsites/stericycle-shared#118]
To improve performance we should add some kind of caching of the query index to the local storage or session storage. This could either be valid for a specific (short) timeframe or per session. Ideally we would have some global function to do all of this. All current fetches of the query index should use this function instead of implementing their own fetch.

**Comment by dkuntze** [comment]
I have this in a couple of my blocks that pull from the query-index. It might not be a bad idea to make it a global function and make use of it everywhere.

**Comment by jindaliiita** [comment]
@dkuntze I am working on this and i am planning to store query-index details in the window object. We have done something similar in one of the other projects.

**Comment by dkuntze** [comment]
I was using the sessionstorage, but I will defer to you.

**Comment by jindaliiita** [comment]
Saved in the sessionstorage with an expiry of 5 minutes.
https://github.com/aemsites/stericycle-shared/pull/124
