### ISSUE TITLE
Column Block Variant with background image

### ISSUE THREAD

**Issue by jindaliiita** [aemsites/stericycle-shared#120]
Columns block with a background image and columns of unequal size.

URL: https://www.shredit.com/en-us/who-we-serve/healthcare

<img width="1724" alt="Screenshot 2024-08-21 at 10 21 40 PM" src="https://github.com/user-attachments/assets/195516db-5ffc-486f-abbd-ff03397db43b">

**Comment by allanhero** [comment]
Hi, I was checking this and it matches this other issue. They are related, right?
Issue: https://github.com/aemsites/stericycle-shared/issues/71
PR: https://github.com/aemsites/stericycle-shared/pull/84
Page:https://main--shredit--stericycle.aem.live/en-us/who-we-serve/small-business

**Comment by jindaliiita** [comment]
Completed via https://github.com/aemsites/stericycle-shared/issues/71
