### ISSUE TITLE
Inconsistent and broken query-index

### ISSUE THREAD

**Issue by kronnox** [aemsites/stericycle-shared#127]
There are currently multiple inconsistencies or errors in our index (and/or the source page metadata it was generated from):

- [ ] The sheet names should correspond to the media type name e.g. `shared-blog` should be `shared-blogs`
- [ ] The media-type column is missing the media type on a lot of pages especially infographics and info-sheets
- [ ] The media-type for videos is lowercase while the media-type for everything else is capitalized-case. This should be consistent and I would argue lowercase would be the better choice here; this way the case can be easily ignored for search and filters.

**Comment by jindaliiita** [comment]
@dkuntze Can you please check if this issue is relevant or not because i am not sure about the exact case for which this issue was created.
