### ISSUE TITLE
Infographic QA - Feedback 

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#137]
Hey Darin,
Did a review of the infographic pages. I have listed my feedback below.

•	Line spacing appears to be off between bullets, body copy, and headlines. It seems too tight in most areas but there are random sections where it is larger. E.g. between first and second line on “2.Pay Attention to Information Destruction section” on https://main--shredit--stericycle.aem.live/en-us/resource-center/infographics/6-tips-to-protect-your-business-from-fraud 
•	Hyperlinks should be underlined – flagged this on Blog Review as well 
•	Frequently Asked Questions on https://main--shredit--stericycle.aem.live/en-us/resource-center/infographics/6-tips-to-protect-your-business-from-fraud seems to have a random hyperlink that goes to the page itself 
•	Internal links are resulting in 404.  Assume this is because the pages linked to haven’t been migrated but just want to be sure. 
•	Need to include page properties listed in ticket below to all pages: https://github.com/aemsites/stericycle-shared/issues/128 
•	Missing you May Also Like section along the bottom of the page. This will be updated today with Autoblock
•	Breadcrumb to come as autoblock 
•	Missing the Newsletter sign-up (dependent on forms)

**Comment by jindaliiita** [comment]
created follow up issue for the breadcrumb
https://github.com/aemsites/stericycle-shared/issues/331

@colinvlasak Closing this issue as it seems some follow up issues are already created and rest issues are closed.
Let us know if you have any concern.
