### ISSUE TITLE
Resource Center - Explore More Parent Page Links Broken

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#146]
Main Infographics parent page (https://main--shredit--stericycle.aem.live/en-us/resource-center/infographics) the links in Explore More Infographics section don’t work. They all go to https://main--shredit--stericycle.aem.live/en-us/resource-center/undefined even though they are showing the assets. Seems to be an issue with the component configuration as it is happening on the Videos page as well.

**Comment by jindaliiita** [comment]
I am not able to reproduce this.
@colinvlasak can you please check if its still reproducible ?

**Comment by jindaliiita** [comment]
Closing this issue as of now. Feel free to reopen

**Comment by colinvlasak** [comment]
@jindaliiita looks to be fixed!
