### ISSUE TITLE
You May Also Like - Date Font Size

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#147]
Date font size is much larger than live site. Can we reduce to match live?

**Comment by jindaliiita** [comment]
@colinvlasak Can you please specify page url here

**Comment by colinvlasak** [comment]
@jindaliiita here's a url with the component - https://main--shredit--stericycle.aem.live/en-us/resource-center/infographics/businesses-cant-ignore-consumers-data-protection-expectations

**Comment by colinvlasak** [comment]
@jindaliiita thanks for updating this!
