### ISSUE TITLE
Site Wide - URL Mapping

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#149]
We recently noticed an issue with the url mapping. It appears that not all urls are the same on the EDS site as the live site. The example below shows the difference. The live url has "--" between awareness and why while the EDS url does not. If the URLs are different from the live site this will result in 404s and potentially broken links.

https://main--shredit--stericycle.aem.live/en-us/resource-center/videos/fraud-prevention-and-awareness-why-it-matters
https://www.shredit.com/en-us/resource-center/videos/fraud-prevention-and-awareness--why-it-matters

Can we ensure that all urls are mapped to match our live site? I presume the discrepancy may be that EDS uses the document title for urls while our live site has the url configured as a custom parameter that may slightly vary from the title (some urls have double "-" or have words removed like "and". 

I'm not sure how broad spread this issue may be but I assume there are a lot of pages that will have the same minor differences. We want to ensure the mapping is clean for launch so we do not run into any issues.

**Comment by colinvlasak** [comment]
cc: @rwcsrichardspencer

**Comment by dkuntze** [comment]
the problem here is that `--` is a url delimiter on aem.live, so it rewrites them to single dashes. We can handle with redirects on those pages.

**Comment by colinvlasak** [comment]
@dkuntze thanks for the quick reply. Can we ensure there is a process in place to review the url discrepancies and ensure the redirects are properly configured for any urls that are changing?

**Comment by dkuntze** [comment]
yeah, I've been flagging them in the page status when I find them

**Comment by colinvlasak** [comment]
@dkuntze @MarquiseRosier wanted to circle back on this and ensure we have a clear solution and next steps. Can you confirm? Where are these flagged and when will be setting up the redirects?

**Comment by jindaliiita** [comment]
@colinvlasak I guess these many pages have this issue. I will add a redirect for these in redirects.json

en-us/about/news-articles/daytime-protect-your-privacy--tips---resources
en-us/about/news-articles/mitigating-cybersecurity-risks-is-not-inherent--it-is-trained
en-us/about/news-articles/risky-business--small-businesses-under--cyber--attack
en-us/about/news-articles/tax-time-in-july--in-the-usa--ways-you-are-notified-if-you-are-t
en-us/about/news-articles/the-great-decluttering-of-2020--the-pandemic-has-inspired-a-clea
en-us/about/news-articles/your-first-line-of-defense-against-data-breaches--employees
en-us/about/press-releases/postnet-partners-with-shred-it-to-provide-industry--leading-docu
en-us/about/press-releases/securit--shred-it-names-vincent-r-de-palma-to-serve-as-president
en-us/blog/7-ways-identity-thieves-steal-personal-id--and-ho
en-us/blog/be-careful-where-you-click--being-aware-of-phishing-tactics-is-k
en-us/blog/the-cost-of-confidential-document-shredding--do-you-know-what-yo
en-us/blog/the-power-of-preparation--data-protection-and-incident-response-
en-us/resource-center/infographics/fraud---identity-theft-prevention--it-starts-with-awareness
en-us/resource-center/infographics/information-security--looking-at-big-business-and-small-business
en-us/resource-center/infographics/knowing-when-to-shred---a-decision-tree
en-us/resource-center/infographics/national-consumer-protection-week--are-you-safeguarding-your-cus
en-us/resource-center/infographics/the-eu-general-data-protection-regulation--gdpr----you
en-us/resource-center/info-sheets/hotel---event-space-security-checklist
en-us/resource-center/info-sheets/information-security-procedures--practices---checklist
en-us/resource-center/info-sheets/secure-recycling--avoid-the-blue-bin
en-us/resource-center/info-sheets/why-shredding-companies-are-not-all-the-same---or-equally-secure
en-us/resource-center/newsletters/playing-it-safe--document-destruction-best-practices
en-us/resource-center/newsletters/security-breach--it-ll-never-happen-to-me-
en-us/resource-center/newsletters/small-actions-for-big-wins---the-information-security-checklist
en-us/resource-center/podcasts/hipaa---hitech--what-you-need-to-know
en-us/resource-center/podcasts/know-when-to-hold-it--know-when-to-shred-it
en-us/resource-center/videos/hipaa-compliance--securing-your-company-s-patient-and-personal-i
en-us/resource-center/videos/shred-it-data-protection-report--10-years-of-information-securit
en-us/resource-center/videos/tax-season--data-security-insights-2021
en-us/resource-center/videos/fraud-prevention-and-awareness--why-it-matters
en-us/service-locations/central-pa---lancaster
en-us/service-locations/mobile---biloxi
en-us/service-locations/new-york--long-island
en-us/resource-center/podcasts/know-when-to-hold-it--know-when-to-shred-it
en-us/resource-center/podcasts/hipaa---hitech--what-you-need-to-know

**Comment by jindaliiita** [comment]
@colinvlasak  Do you have any example of **and** word pages where **and** is getting removed, which you have stated above.

**Comment by colinvlasak** [comment]
@jindaliiita it looks like the removal of and is not actually a problem. I couldn't find any examples when comparing against our current CMS.

Thanks for putting together the list above. How did you pull those URLs? Are we able to do a scan of our live site urls vs. EDS urls to see if there are any further discrepancies? Want to ensure there are no issues for launch

**Comment by jindaliiita** [comment]
No, @colinvlasak, I just checked the status page sheet and identified a pattern with '--' as well as a pattern with just '-' at the end. Attached is the final sheet for the redirects.json.

I have two queries: A few URLs related to news articles are currently being redirected to third-party URLs. What should we do in that case? For example:
https://www.shredit.com/en-us/about/news-articles/risky-business--small-businesses-under--cyber--attack

Additionally, some blog URLs contain junk data, such as:
https://www.shredit.com/en-us/blog/the-power-of-preparation--data-protection-and-incident-response-

[imp_redirects.xlsx](https://github.com/user-attachments/files/17511067/imp_redirects.xlsx)

**Comment by jindaliiita** [comment]
@colinvlasak I have added the corresponding redirects, which you can find in the attached sheet. I have also added a remarks column for your clarity.
Let me know if you have any concerns. I am closing this issue for now.

[redirects_changes.xlsx](https://github.com/user-attachments/files/17537570/redirects_changes.xlsx)

cc @MarquiseRosier @kronnox

**Comment by colinvlasak** [comment]
@jindaliiita looks good from my end.

@rwcsrichardspencer can you give this a review since it pertains to redirects
