### ISSUE TITLE
Service Tile - Text Wrapping

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#153]
The text on the tiles is too close to edges. Should have more padding around edges to keep text more confined. This is most apparent on One-Time and Regular tiles.

Example on: https://main--shredit--stericycle.aem.live/en-us/service-locations/boston

**Comment by colinvlasak** [comment]
![image](https://github.com/user-attachments/assets/f8623c55-fafc-4e5c-898a-56d72845af85)

**Comment by jindaliiita** [comment]
Will be covered via https://github.com/aemsites/stericycle-shared/pull/259
