### ISSUE TITLE
Locations - Mobile Form Placeholder Configuration 

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#156]
Form placeholder is rendering below the Blog section on Mobile. The form should be replaced by a CTA button in the Hero banner on Mobile. This is the current functionality on our live site. 

Example on our live site - https://www.shredit.com/en-us/service-locations/boston

**Comment by colinvlasak** [comment]
@ravise5 this issue is still not fixed on mobile. The form is still appearing at the bottom of the page and there is no CTA button in the header. Mobile experience should match the live site.

**Comment by ravise5** [comment]
Can you clear cache and try once?

**Comment by ravise5** [comment]
![image](https://github.com/user-attachments/assets/0fd55bfe-ca63-4a39-9d07-c159cfb64189)

**Comment by colinvlasak** [comment]
@ravise5 looks good now that I cleared cache. Is there a way to force clear the cache within EDS so this isn't an issue for other users?

**Comment by ravise5** [comment]
This is user browser cache, that's something not in our control. CDN cache invalidates as soon as you change anything in content or code.

**Comment by ravise5** [comment]
Can we close this issue?

**Comment by colinvlasak** [comment]
Got it. Yeah will close.
