### ISSUE TITLE
Locations- Missing Location Info

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#157]
Missing location information (address & drop-off) on: https://main--shredit--stericycle.aem.live/en-us/service-locations/albuquerque 

Should be in the sidebar under the form placeholder

**Comment by colinvlasak** [comment]
@MarquiseRosier this is still not fixed.

**Comment by jindaliiita** [comment]
<img width="455" alt="Screenshot 2024-10-23 at 4 52 30 PM" src="https://github.com/user-attachments/assets/dfbb03ce-8e75-4bc5-927c-13f6ccb39c25">

@colinvlasak A couple of points here: Are the sales and customer service numbers fixed? Should I hard code them in the code, or would you prefer to control them using metadata?

Secondly, how are you currently displaying nearby locations? Will they also be derived from metadata, or will there be logic to fetch them based on distance?

**Comment by colinvlasak** [comment]
@jindaliiita the phone numbers should stay consistent for all of our local pages in the US. Can we have it set up so that they are hardcoded but there is reference in a spreadsheet or somewhere we can easily manually update the number on our end if needed then it would update across all of the pages? Essentially want an author to be able to change it easily (but do not need to be able to edit it at page level).  

Please note we also need to ensure whatever solutions we are using will work with Invoca (our call tracking platform). I believe the current Invoca script on our site just looks for specific phone numbers and then dynamically changes them and adds in the tracking. Just want to ensure that will work with EDS. That may be a separate item as it applies sitewide but wanted to mention.

For nearby locations I think using logic to fetch them would be ideal. Can we set it up so that pulls all locations within say a 50 miles radius of the location?
