### ISSUE TITLE
Service Location Map

### ISSUE THREAD

**Issue by dkuntze** [aemsites/stericycle-shared#158]
![image](https://github.com/user-attachments/assets/b7b1c2d4-3296-44ca-846d-d4c2d3543b32)

- https://www.shredit.com/en-us/secure-shredding-services/drop-off-shredding
- https://www.shredit.com/en-us/service-locations

**Comment by jindaliiita** [comment]
Covered by https://github.com/aemsites/stericycle-shared/pull/167
