### ISSUE TITLE
Header - Design Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#159]
There are a few design issues with the current header in EDS.

**Styling needs to be applied to subnav. Currently spacing/padding/text styling (bold headers), etc. is off
EDS**
![image](https://github.com/user-attachments/assets/39010d79-38ba-47a0-b394-768dc6815be3)

Live
![image](https://github.com/user-attachments/assets/c5be7422-382a-45d1-bafc-6c45f58b4bbd)

**Hover state on top nav should be blue**

EDS
![image](https://github.com/user-attachments/assets/ec7c5c11-7566-4709-ba26-6172480ed330)

Live
![image](https://github.com/user-attachments/assets/371bb06a-5536-4848-9a14-de889b0c9ac8)

**Mobile – main nav link colours don’t match existing (too light)**

![image](https://github.com/user-attachments/assets/0dd3afff-b7ab-4c29-b20d-2bf88505f2f9)

**Comment by bstopp** [comment]
I have an update coming today that would address this

**Comment by colinvlasak** [comment]
@bstopp thanks for the update. Let me know once it is pushed live so I can QA and verify
