### ISSUE TITLE
Header - Find Your Service Center Issue

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#160]
Find Your Service Center doesn’t work in the header. When you click the link nothing happens. Should open a popout menu with the ability to enter location details. 

Should look like this:
![image](https://github.com/user-attachments/assets/95884fc9-9422-442e-bc46-f7c15004316b)

**Comment by colinvlasak** [comment]
@bstopp there are still a few issues here

1. When you enter a zip code or state it just takes you to the https://main--shredit--stericycle.aem.live/en-us/service-locations page with no filtering on the map. It should load the page with the map filtered based on the search. So if you search a zip it should only show the branches on the map near that zip.

2. If you try to use the Find Your Service Center function while on the service locations page it causes a bug. Button turns white and it doesn't do anything.

![image](https://github.com/user-attachments/assets/e748fb55-dbbd-4972-bec8-aa258d1b16a5)

3. The Service Locations link at the bottom of the popout links to the wrong page. Goes to https://main--shredit--stericycle.aem.live/en-us/locations should go to https://main--shredit--stericycle.aem.live/en-us/service-locations

![image](https://github.com/user-attachments/assets/638e7e8d-fb4b-4f00-8f05-c8bed122f4ca)

4. When you click on the Find Your Service Center option the autofill comes up before you click in the search field which covers up the Service Locations link. Can we make it so it only appears once a user clicks in. 

![image](https://github.com/user-attachments/assets/3d4dbff7-a227-45c4-abb8-2fd1c0d35954)

**Comment by bstopp** [comment]
I captured 1 in issue #407  - As this is a bug in the Service Location 

I don't experience issue 2 or 4.

I have opened PR #408 to address 3.

**Comment by colinvlasak** [comment]
@bstopp 2 and 4 are happening on my end and need to be resolved. 

For #2 

- go to https://main--shredit--stericycle.aem.live/en-us/service-locations
- Click on Find You Service Center in top nav
- Enter zip code
- Click Search button
- Move cursor away from search button (box turns white as shown in screenshot)
- This is happening on both Chrome and Firefox

#4 
Looks to be specific to Google Chrome. You will have had to have searched previous terms on the site for this to happen.

**Comment by bstopp** [comment]
Ok - I think i got 2 & 4 fixed. With PR #408 as well

**Comment by colinvlasak** [comment]
@bstopp looks like 2,3, and 4 are fixed through #408 - on https://bug-service-location-url--shredit--stericycle.aem.page/en-us. Can we push them up to live?

Will look out for updates in #407 re: 1

**Comment by bstopp** [comment]
Pushed to live.
