### ISSUE TITLE
Header - Search Funcionality

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#162]
Search function in header doesn't work. When you enter a search query it doesn't return anything.

![image](https://github.com/user-attachments/assets/e1e21d73-2559-4ca6-bc40-68c62c2eaded)

**Comment by colinvlasak** [comment]
@bstopp the search box now allows you to enter search inquiries but it doesn't return results properly.

https://main--shredit--stericycle.aem.live/en-us/search?searchQuery=paper

![image](https://github.com/user-attachments/assets/df06b6c7-4412-4aa1-a78e-e72cac6e76fe)

**Comment by bstopp** [comment]
The header submits to the search page - which is all it can do.

The Site Search block itself is captured in issue #85

**Comment by colinvlasak** [comment]
@bstopp okay as long as the full functionality will be fixed with #85 this can be closed,

**Comment by colinvlasak** [comment]
@bstopp sorry one more small thing here. The "x" doesn't show a clickable element. The mouse shoudl change to the finger pointer from the arrow pointer on hover as it does for the search icon.

![image](https://github.com/user-attachments/assets/d3b61aec-473c-4e1f-806b-91a919e7e8fa)

**Comment by bstopp** [comment]
not sure which browser you're using, but i don't get a hand pointer on the magnifying class nor the 'X', in FireFox or Chrome. 🤔

**Comment by colinvlasak** [comment]
@bstopp it's happening on Chrome and Firefox on my end

When I hover over the magnifying glass it shows the hand pointer (desired behaviour). When I hover over the x it stays the classic pointer mouse (should be hand pointer to indicate it's a link/button)

![image](https://github.com/user-attachments/assets/e12729ca-d995-4704-8ef5-e78ed89dc81e)

**Comment by colinvlasak** [comment]
@bstopp still seeing same thing on https://main--shredit--stericycle.aem.live/en-us. 

When I hover over the magnifying glass it shows the hand pointer (desired behaviour). When I hover over the x it stays the classic pointer mouse (should be hand pointer to indicate it's a link/button)

**Comment by bstopp** [comment]
Check https://bug-search-hover--shredit--stericycle.aem.page/en-us from #422 ?

**Comment by colinvlasak** [comment]
@bstopp pointer is working as expected (hand cursor on hover on x and magnifying glass) on - https://bug-search-hover--shredit--stericycle.aem.page/en-us

**Comment by bstopp** [comment]
I'll fix the full search functionality on the results page with a new PR and address #85
