### ISSUE TITLE
Locations - You may Also Like Content Widget - Rendering Issue

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#168]
There are red bullets showing beside the image on the Resource Center link components on the location page. These should not be appearing. 

![image](https://github.com/user-attachments/assets/70e9ff61-1e46-4258-8ddf-9608c09fb343)

Example: https://main--shredit--stericycle.aem.live/en-us/service-locations/reno

**Comment by jindaliiita** [comment]
There are multiple issues reported regarding the orange icon. I will look into https://github.com/aemsites/stericycle-shared/issues/173 and rest all will be related to this.

**Comment by jindaliiita** [comment]
Will be handled via https://github.com/aemsites/stericycle-shared/pull/260
