### ISSUE TITLE
orange triangles everywhereee

### ISSUE THREAD

**Issue by MarquiseRosier** [aemsites/stericycle-shared#173]
Red Triangles are a bit heavy handedly applied; but relevant in several places; making it difficult to make rules to determine where they should be applied. Currently, we apply a :not() pseudo-selector on one class to be exempted from the rule; but this is not scalable and can turn chaotic as more types of lists emerge that need to be exempt. @dkuntze @jindaliiita we clearly need to figure out a quick way to alleviate this. I've handed this task over to @jindaliiita since it seems he may be better suited for it: pages with the triangle lists showing up 

1) https://in-the-news--shredit--stericycle.aem.page/en-us
2) https://in-the-news--shredit--stericycle.aem.page/en-us/resource-center/infographics

<img width="852" alt="Screenshot 2024-09-10 at 2 09 34 AM" src="https://github.com/user-attachments/assets/a3e78078-45f5-441d-8826-2ff7854926c1">

**Comment by jindaliiita** [comment]
I have removed styling for orange icon which was added on every li.
If any one wants to have orange icons on list then they can  add "list-style-orange-triangles" on section metadata.
