### ISSUE TITLE
Locations - Schema

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#176]
EDS location pages are missing schema. Schema for these pages should match existing site including:

- Organization (business) schema
- Location Schema, 
- FAQ schema (only on some pages currently)

**Comment by jindaliiita** [comment]
@rwcsrichardspencer / @colinvlasak Is this issue same as https://github.com/aemsites/stericycle-shared/issues/363
If yes, then we can close this one.
