### ISSUE TITLE
Map - Load Time

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#195]
•	Map is very slow to load (takes 4 or 5 seconds after everything else loads). Makes landing experience jarring and a bit confusing. Can this be improved?

![image](https://github.com/user-attachments/assets/ae93c612-0ee2-4429-afc2-42e5a419d3bc)

**Comment by colinvlasak** [comment]
@rwcsrichardspencer can you weigh on in this one? Static map on load sounds like it could be a feasible option.

**Comment by jindaliiita** [comment]
Covered via https://github.com/aemsites/stericycle-shared/pull/208.

@colinvlasak I have added default image for both service location and drop-off-shredding pages.
If you want to change the image, you can directly change in the doc itself.

![luxa org-opacity-changed-Screenshot 2024-09-19 at 8 38 04 PM](https://github.com/user-attachments/assets/5d7a01d9-f59d-4d48-97a8-53d6630f81f1)
