### ISSUE TITLE
External Link - Open In New Tab

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#196]
Can we set all external links to automatically open in a new tab?

When reviewing the drop-off pages I noticed that the Drop-off buy now links and Get Directions Link open in same tab. Would be best to open in a new tab if possible.

**Comment by jindaliiita** [comment]
Will be covered via https://github.com/aemsites/stericycle-shared/pull/191

**Comment by jindaliiita** [comment]
Will be covered via https://github.com/aemsites/stericycle-shared/pull/191
