### ISSUE TITLE
Locations Page - Content Editing Option Missing

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#203]
Locations Page: Need to be able to edit content (title and instructions) above map as an author
o	Find the nearest drop off shredding location to you:
	Please enter your location (zip code or city)

![image](https://github.com/user-attachments/assets/ecc32412-1f7c-40f3-933e-f5e92a798dbe)

![image](https://github.com/user-attachments/assets/d486c532-562b-4d7a-8350-29fbfebeafce)

**Comment by jindaliiita** [comment]
Covered via https://github.com/aemsites/stericycle-shared/pull/208
