### ISSUE TITLE
Map/Search - Locations Links 404

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#204]
The Go To Shredit "Location" links results in a 404. e.g. - https://main--shredit--stericycle.aem.live/en-us/service-locations/shred-it-kansas-city

![image](https://github.com/user-attachments/assets/527e7432-c71a-4450-a5ab-e137e5fe125a)

**Comment by colinvlasak** [comment]
It looks like the systems is adding "shred-it-" in the url slug ahead of the city name which is causing the issue. 

Rendering:
https://main--shredit--stericycle.aem.live/en-us/service-locations/shred-it-kansas-city 

Should be 
https://main--shredit--stericycle.aem.live/en-us/service-locations/kansas-city

**Comment by jindaliiita** [comment]
Covered via https://github.com/aemsites/stericycle-shared/pull/208
