### ISSUE TITLE
Heading Colour Inconsistencies

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#212]
We have noticed that the heading colours are inconistent across the site. Can we ensure all main heading (H1, H2) that are on white or light gray backgrounds are dark gray (vs. bright blue)?
![image](https://github.com/user-attachments/assets/507f8faa-2b82-4919-a255-909a1123edd5)

**Comment by jindaliiita** [comment]
@colinvlasak Can you please provide any sample url here in order to check.
Thanks

**Comment by jindaliiita** [comment]
One thing we can do for now is handle the grey-background cases.

**Comment by colinvlasak** [comment]
@jindaliiita can you confirm what changes were made? Did you just update the colours for the gray background text? Is there a way for us to manually change the text colours in the word docs?
