### ISSUE TITLE
Inline Form Placeholder

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#213]
Can we add a placeholder page section for the inline form on the Service pages and any other applicable pages that include inline forms? You guys did this for the local template and it is really helpful. It will help to ensure formatting of the pages is accurate (rendering and spacing)

![image](https://github.com/user-attachments/assets/55b617b8-1517-49d8-a18c-2ec3aff3f368)

**Comment by jindaliiita** [comment]
@MarquiseRosier Assigning this to you, as I believe you are handling this via https://github.com/aemsites/stericycle-shared/pull/274.

**Comment by bstopp** [comment]
Form is on page. no placeholder needed.
