### ISSUE TITLE
Hard Drive Images - Too Large

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#214]
Images on Hard Drive Page are way too big. Need to be scaled down significantly to match live site. We use column for this currently. How can we solve without column row to control image size?

Page: https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/hard-drive-destruction

![image](https://github.com/user-attachments/assets/fd5c7573-a8fa-43b4-a2af-958fae250d1e)

**Comment by jindaliiita** [comment]
will be fixed via https://github.com/aemsites/stericycle-shared/pull/258

**Comment by colinvlasak** [comment]
@MarquiseRosier @jindaliiita 

This is the issue that just came back - https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/hard-drive-destruction?fd

**Comment by jindaliiita** [comment]
Just an authoring change
Added **native-image-sizes, center-align** variant in the columns block

<img width="621" alt="Screenshot 2024-12-06 at 9 06 48 AM" src="https://github.com/user-attachments/assets/dbb772bb-3d0a-4ae1-93a6-ad0bada61ec1">

**Comment by colinvlasak** [comment]
@jindaliiita great, thank you! What does the img-33 label do?
