### ISSUE TITLE
Risk Assessment Styling Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#217]
•	CTA for Risk Assessment should be styled as secondary (blue vs. yellow)
o	On https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/hard-drive-destruction 
![image](https://github.com/user-attachments/assets/b99fec4c-9487-483b-b80e-8af1d85116d8)
 
•	CTA Missing and spacing is off for Risk Assessment on: https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/specialty-shredding-service 

![image](https://github.com/user-attachments/assets/e3504ecf-8503-4dff-a002-00d41c46d661)

**Comment by jindaliiita** [comment]
Will be covered via https://github.com/aemsites/stericycle-shared/pull/258
