### ISSUE TITLE
Video Embed Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#218]
•	Video Rendering is off. Should use proper brand styles (Stericycle videos are green, SID Videos are blue) and have a keyline around video frame
o	On - https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/myshredit but applies to all video embeds

![image](https://github.com/user-attachments/assets/761f3fbf-355c-4d60-8392-56aff2b61eeb)

**Comment by jindaliiita** [comment]
This is a background color change on the iframe elements. I don't think we can control it since the iframe's source and its parent are different.
@dkuntze I am not sure if there is any way to do it.
Any suggestions would be appreciated.

**Comment by jindaliiita** [comment]
Currently we have done changes for Wistia video player. If this is applicable for other players also then feel free to reopen this issue or create a new one.
