### ISSUE TITLE
T&Cs - Convert To Fragment and Update Styling

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#225]
Needs to be authored as a content fragment. We use this across several pages and update the date regularly. Need to be able to update once and have it apply across the site. 

Example on bottom of https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/one-off-shredding-service 

Font size of this section should be reduced to small or very small (see live example below)

![image](https://github.com/user-attachments/assets/53739d84-f62c-48c3-82f3-658a4aa28665)

**Comment by jindaliiita** [comment]
@colinvlasak Can you point me to the other pages where these terms and conditions are present, aside from the one you've mentioned ?

**Comment by jindaliiita** [comment]
https://github.com/aemsites/stericycle-shared/pull/269#issuecomment-2390898952

**Comment by colinvlasak** [comment]
@jindaliiita you can see the full list of usages in AEM if you click into the experience fragment

https://author-p29452-e94470.adobeaemcloud.com/ui#/aem/aem/experience-fragments.html/content/experience-fragments/shred-it/us/en/site/offer-terms-conditions

There are two variations of the XF. You can see what pages leverage it under References > Usages when you click imto each.

![image](https://github.com/user-attachments/assets/77df811e-e7c9-474e-a00d-75bc9ae45428)


![image](https://github.com/user-attachments/assets/386bac8a-c419-4342-a34a-e757497e9bc7)
