### ISSUE TITLE
Section decoration

### ISSUE THREAD

**Issue by kronnox** [aemsites/stericycle-shared#30]
![Screenshot 2024-06-13 at 17 45 29](https://github.com/aemsites/stericycle-shared/assets/28481491/e49d5039-ba3f-45e7-8ddb-1f7b014e00e5)

Example from https://www.shredit.com/en-us/secure-shredding-services/specialty-shredding-service

---

![Screenshot 2024-06-13 at 17 46 07](https://github.com/aemsites/stericycle-shared/assets/28481491/fd68b41b-b298-4e14-a700-4d265c8df268)

Example from https://www.shredit.com/en-us/who-we-serve/small-business

**Comment by allanhero** [comment]
@dkuntze  @kronnox  @seanathero I am working on this separately in the following issues: 
https://github.com/aemsites/stericycle-shared/issues/70
https://github.com/aemsites/stericycle-shared/issues/71

**Comment by allanhero** [comment]
Deployed!
