### ISSUE TITLE
Marketing Pages - Bullets Not Rendering

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#304]
Bullets are not rendering properly – This is happening across all Marketing pages

e.g. https://main--shredit--stericycle.aem.live/en-us/marketing/25purge 

![image](https://github.com/user-attachments/assets/2841a5f0-2746-4364-8c6e-84896b7823d4)
![image](https://github.com/user-attachments/assets/b3a89695-2cb9-4ae4-bf88-a9ab0b450ce8)

**Comment by MarquiseRosier** [comment]
@colinvlasak I think we can call this resolved! Thanks for this feedback!

**Comment by colinvlasak** [comment]
@MarquiseRosier it looks to be fixed on the Marketing pages but is still occurring in other places across the site. Can you ensure the bullet rendering is fixed across the entire site? It seems to be happening across a wide range of page types. 

Examples:

https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/paper-shredding-services
![image](https://github.com/user-attachments/assets/c691a3bc-d037-4c16-bffa-7fd4119ecdd5)

https://main--shredit--stericycle.aem.live/en-us/resource-center/info-sheets/knowing-what-to-shred-is-vital
![image](https://github.com/user-attachments/assets/1ec1fb04-cd44-4ad6-876e-90719cb6882a)

**Comment by MarquiseRosier** [comment]
This looks resolved now!

**Comment by bstopp** [comment]
All bullets appear to be displaying as desired.
