### ISSUE TITLE
Service Boxes - Vertical Alignment

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#306]
Boxes should be stretched to align vertically so that they are even

Example : https://main--shredit--stericycle.aem.live/en-us/marketing/campaign-page-optimized 

![image](https://github.com/user-attachments/assets/8c37b6cc-1f81-4c21-b5d1-3ae24bc131ac)

**Comment by MarquiseRosier** [comment]
@colinvlasak on the original site; this is not the case

https://www.shredit.com/en-us/marketing/campaign-page-optimized

**Comment by jindaliiita** [comment]
Closing this as changes not required

**Comment by colinvlasak** [comment]
@jindaliiita @MarquiseRosier is this difficult to implement? We want this to be the case across the site. In most cases it is but it seems in some instances on our existing site it may not be. We would like this component to auto stretch to be even on all pages.

**Comment by jindaliiita** [comment]
Fixed
