### ISSUE TITLE
New SEM Pages - Content Rendering Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#309]
Main Content section not rendering properly. Need to add inline form for two column layout. Ensure icons and text lay cleanly with background image below (currently overlapping) 

![image](https://github.com/user-attachments/assets/156b7c5f-b492-4f8c-8eb7-727afc5da0e3)

Should look like:
![image](https://github.com/user-attachments/assets/bb3707ef-9550-43ea-aa92-f8d0c48c07cf)

**Comment by MarquiseRosier** [comment]
Oh @colinvlasak apologies, i closed this issue according to the original issue list! Thanks for adding some more context!

**Comment by colinvlasak** [comment]
@MarquiseRosier looks much better. Can we move the background image up a bit to match live?

EDS:

![image](https://github.com/user-attachments/assets/b5c8a3ff-64f0-4b20-b179-a92372bdaf15)



Live:
![image](https://github.com/user-attachments/assets/00e06953-fee4-44dd-bcbb-e08e6ef49032)
