### ISSUE TITLE
NEW SEM Page - Trusted by Leading Organizations Alignment Issue

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#314]
Trusted by Leading Organizations – Alignment is off. Logos should be justified to the edges on left and right '

Examples: https://main--shredit--stericycle.aem.live/en-us/marketing/bulk-paper-shredding and https://main--shredit--stericycle.aem.live/en-us/marketing/hard-drive-destruction-service  (this applies to all pages using this layout)

![image](https://github.com/user-attachments/assets/7998deb3-8287-4446-9a50-e96d9bde355f)

**Comment by jindaliiita** [comment]
It is already taking up the full space. The Luxottica image contains a background that is occupying space. So, I think you need to modify the Luxottica SVG.
Closing this as of now.
