### ISSUE TITLE
Marketing Footer Rendering Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#316]
**New Marketing Page**

Example: https://main--shredit--stericycle.aem.live/en-us/marketing/hard-drive-destruction-service 

Lots of extra spacing, random extra phone and get a quote at top, horizontal divider uneeded. 

![image](https://github.com/user-attachments/assets/f5ba7a8b-a989-4782-997e-47ef52e42c91)

Should be:
![image](https://github.com/user-attachments/assets/0e75af0e-dcb8-43bf-aa66-7821d642a8aa)

Other Marketing Pages:

Example: https://main--shredit--stericycle.aem.live/en-us/marketing/campaign-page-optimized

Showing extra vertical divider and unnecessary vertical space  

![image](https://github.com/user-attachments/assets/6e26a127-1124-4310-8b69-d65216488ae9)

**Comment by MarquiseRosier** [comment]
@colinvlasak this should be settled

**Comment by colinvlasak** [comment]
@MarquiseRosier looks better. Can we reduce the extra padding between the top section and the horizontal divider? Should be same amount of padding as the divider and the "In compliance with the America..." below it.

![image](https://github.com/user-attachments/assets/a7a7e4df-ad25-4e47-a097-31445311bcbf)
