### ISSUE TITLE
Heading Inconsistencies in Box Layout 

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#318]
Font colour should be dark blue vs. Light blue and should be H3 vs. H2 – this applies to a large portion of the pages

o	e.g. https://main--shredit--stericycle.aem.live/en-us/marketing/document-destruction-service-new

![image](https://github.com/user-attachments/assets/a0fe7a98-2399-4d3f-99bc-c53850c2209c)

**Comment by jindaliiita** [comment]
Fixed
