### ISSUE TITLE
New SEM Page Inline Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#319]
Example: https://main--shredit--stericycle.aem.live/en-us/marketing/shred-it-document-destruction-inline 
o	:shred-it-a-20stericycle-20solution-logo-white: showing on the page
o	Form should be inline to the right of the content not below
![image](https://github.com/user-attachments/assets/cb8c4209-292a-4a41-a367-35bb643d2504)
o	25 Off Badge and text missing 
![image](https://github.com/user-attachments/assets/fc68375e-f266-4d1e-ab87-f18f1bb5c42d)

**Comment by colinvlasak** [comment]
@MarquiseRosier the 25% off badge is rendering a bit off. Text should be centered and no line spacing between words. Yellow block should be perfectly aligned to the icon above. 

EDS:
![image](https://github.com/user-attachments/assets/93de4a49-e3d1-40d5-aa2a-99bfc7f942a3)

Live:
![image](https://github.com/user-attachments/assets/b2149fde-b559-44d9-b155-ab95ab492620)

**Comment by MarquiseRosier** [comment]
will be fixed in the referenced PR
