### ISSUE TITLE
Hard Drive Marketing Page Rendering Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#321]
Example: https://main--shredit--stericycle.aem.live/en-us/marketing/shred-it-hard-drive-destruction 
o	Image rendering way too big 
o	Should have inline form placeholder (two column)

Should look like:
![image](https://github.com/user-attachments/assets/713900c0-ba3c-4ab8-a79d-79e12931cfad)

**Comment by jindaliiita** [comment]
Closing this as its now resolved
