### ISSUE TITLE
SEM page - Spacing/Layout Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#322]
Example: https://main--shredit--stericycle.aem.live/en-us/marketing/shred-it-paper-shredding-services 

o	Spacing issues with content
o	Headings different colours and sizes. Should be dark blue and H3

![image](https://github.com/user-attachments/assets/9dffaa32-b81e-49ef-94bc-b5dbd36b0236)

**Comment by jindaliiita** [comment]
Its fixed now
