### ISSUE TITLE
T&Cs - SEM Pages

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#323]
Terms & Conditions should be a fragment on all pages with text styled much smaller. We have T&Cs across multiple pages and want to ensure we only need to update them once. 

![image](https://github.com/user-attachments/assets/28a8312a-17a2-4ea6-9eaa-4ce79d62cc73)

Should be a fragment with small text that looks like this:

![image](https://github.com/user-attachments/assets/3052cbf4-b4af-4328-8a0c-0bfbe7908c68)

**Comment by jindaliiita** [comment]
@colinvlasak I have manually added for some of the pages.
If you find any other page then kindly include https://main--shredit--stericycle.aem.page/en-us/fragments/t-and-c as fragment.

<img width="640" alt="Screenshot 2024-10-10 at 2 14 47 PM" src="https://github.com/user-attachments/assets/7e84eb26-6428-4d37-b9f3-f58d843a7cfa">

**Comment by jindaliiita** [comment]
Closing this as of now.

**Comment by colinvlasak** [comment]
@jindaliiita thanks for making the update. Are we able to run a script to identify any pages that still have the T&Cs as text and replace them with the fragment? @dkuntze mentioned we should be able to do this with doc based editing.

**Comment by jindaliiita** [comment]
@colinvlasak These are the only pages left with T&Cs:
- en-us/fragments/t-and-c --> This is expected since it’s the T&Cs fragment.

I’m unsure about the following two cases:
- en-us/footer-short
- en-us/marketing/shred-it-pricing

@MarquiseRosier Do you know the above two cases ?

**Comment by MarquiseRosier** [comment]
Yeah; @jindaliiita we need to make an issue for possibly another variant of footer with the T&C in it!

**Comment by colinvlasak** [comment]
@MarquiseRosier @jindaliiita want to ensure we are on the same page here. To be clear - All of the pages that previously had individual authored T&Cs have been replaced by the T&Cs fragment except for the cases listed above? If so that is great!

Can you confirm what en-us/footer-short is? I tried to review the page https://main--shredit--stericycle.aem.live/en-us/footer-short but it results in a 404

As for: https://main--shredit--stericycle.aem.live/en-us/marketing/shred-it-pricing

I think we can delete the entire section highlighted below and just replace it with the T&Cs fragment

![image](https://github.com/user-attachments/assets/5ed1ef80-93e7-46af-833c-10c71c1edaaf)

**Comment by jindaliiita** [comment]
@colinvlasak I have made changes to https://main--shredit--stericycle.aem.live/en-us/marketing/shred-it-pricing.

For https://main--shredit--stericycle.aem.live/en-us/footer-short, the page was not published, which is why you were seeing a 404 error.

I'm not sure where this page is being used, so I tagged @dkuntze and @MarquiseRosier for clarification.

**Comment by jindaliiita** [comment]
Closing this as its fixed. Deleted page https://main--shredit--stericycle.aem.live/en-us/footer-short as it seems to br wrongly added
