### ISSUE TITLE
Industry Pages - Hero Banners Cut off/boxed 

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#332]
Hero Banners cut off/boxed – should span full width – this applies to all Who We Serve Pages
o	Images also pixelated
o	Example: https://main--shredit--stericycle.aem.live/en-us/who-we-serve/accountants 

This is happening on all of the Who We Serve Pages

![image](https://github.com/user-attachments/assets/d82a32fe-f6ca-42d2-8bf5-d6b0c09385da)

**Comment by MarquiseRosier** [comment]
results look fine now at https://main--shredit--stericycle.aem.live/en-us/who-we-serve/accountants
but @jindaliiita if you can take a look at why images are blurry that'd be amazing :)
