### ISSUE TITLE
Industry Pages - Spacing Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#338]
End of Page spacing Issues
o	Should not be a gap between the image and the footer

![image](https://github.com/user-attachments/assets/d0a4eeb0-dad1-4553-8d23-3ed932a17d35)

Example: https://main--shredit--stericycle.aem.live/en-us/who-we-serve/finance

**Comment by MarquiseRosier** [comment]
Hey @colinvlasak just want to check on this because on the current site 
https://www.shredit.com/en-us/who-we-serve/finance

on the mobile view there is a gap; just want to check in; is it a different policy when mobile; that there is a gap between last element and footer?

**Comment by colinvlasak** [comment]
@MarquiseRosier there shouldn't be a gap on mobile either. It looks like it might be a bug on the tablet set-up. Full mobile looks to show no gap on live. 

Mobile:
![image](https://github.com/user-attachments/assets/b589b018-0558-4472-8211-433598a75572)

Tablet:

![image](https://github.com/user-attachments/assets/d8478ccb-f219-4fef-84e3-3920d041b64d)


Please note the lack of spacing between this section and the footer should only apply to this layout (background image with stats on Industry pages). Not all content sections across the site.
