### ISSUE TITLE
Industry Pages - Stats Section Rendering Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#339]
•	Stats section not rendering properly – this applies to most of the who we serve pages

Examples:
o	https://main--shredit--stericycle.aem.live/en-us/who-we-serve/auto 
o	https://main--shredit--stericycle.aem.live/en-us/who-we-serve/c-suite-executive 

EDS
![image](https://github.com/user-attachments/assets/bc787583-ae06-4254-82cc-27c3a7abf801)

Should be:
![image](https://github.com/user-attachments/assets/09992fc1-8b9c-468c-8ccd-1fd86348be5d)

It is rendering slightly better on https://main--shredit--stericycle.aem.live/en-us/who-we-serve/accountants but there are still issues:
	Image is too large
	Image bleeding into text
	Learn More should be showing as a secondary button (white background) 
![image](https://github.com/user-attachments/assets/6db78ff2-3324-47b2-b9fa-a936d54ef004)

**Comment by MarquiseRosier** [comment]
@colinvlasak this should be fixed thanks to @jindaliiita

**Comment by colinvlasak** [comment]
@MarquiseRosier @jindaliiita looks much better. One final issue. There should be spacing between the section and the footer so they don't bleed into each other.

EDS

![image](https://github.com/user-attachments/assets/a5a57b8e-de5b-4cda-bb4d-3a126df24308)

Live site:

![image](https://github.com/user-attachments/assets/a4e70151-a2f1-42e1-9e1e-8a24d7180509)
