### ISSUE TITLE
Industry Pages - Testimonial Rendering Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#340]
•	Styling not properly applied to testimonial section on: https://main--shredit--stericycle.aem.live/en-us/who-we-serve/auto 

![image](https://github.com/user-attachments/assets/73ef487e-3e54-4193-86c6-4f872c02c753)

Should be:

![image](https://github.com/user-attachments/assets/833e4ff1-6db3-4fdc-a2f8-b15063047927)

**Comment by MarquiseRosier** [comment]
Fixed @colinvlasak

**Comment by colinvlasak** [comment]
@MarquiseRosier styling is fixed but the image is wrong. It should be the images of the cars since this is automotive. 

EDS
![image](https://github.com/user-attachments/assets/bc9a53ee-9fdb-41a3-a2b5-ce02096f8cf8)


Live: 
![image](https://github.com/user-attachments/assets/d759a711-21db-4390-8875-7aa68e19b449)

**Comment by jindaliiita** [comment]
@colinvlasak Image changed for this

**Comment by jindaliiita** [comment]
Closing this as styling and spacing is being tracked via
https://github.com/aemsites/stericycle-shared/issues/338
