### ISSUE TITLE
Pricing Page - Column Icon Sizes

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#344]
The icons are two different sizes on the pricing page. This is causing the entire top section to be misaligned. The text and icons for One Time and Regular should be the same size so everything is vertically aligned. The copy below and the CTA button should also be vertically aligned.

Page: https://main--shredit--stericycle.aem.live/en-us/secure-document-destruction-and-shredding-prices

![image](https://github.com/user-attachments/assets/31904475-aaf1-4193-8966-d36eefb39858)

The bullets also aren't rendering properly (this is a site wide issue noted in another ticket)

**Comment by jindaliiita** [comment]
Now, rendering fine. So, closing this issue

**Comment by colinvlasak** [comment]
@jindaliiita this is still slightly off. The text isn't aligned. I think the icons are still a bit too big,

![image](https://github.com/user-attachments/assets/956c7284-2b8f-4495-8b35-d653f6650cbf)


Everything should be aligned.

Live site:

![image](https://github.com/user-attachments/assets/e1345b39-9132-46fc-b171-885b807b1d6f)

**Comment by colinvlasak** [comment]
@jindaliiita Top section looks much better. I think the button and description text are just a touch lower on the right columnd vs. the left. Can you take another look?

![image](https://github.com/user-attachments/assets/265df4c9-2dcf-4874-95a0-3dd092c99015)

**Comment by colinvlasak** [comment]
@MarquiseRosier @jindaliiita 

another issues that was fixed which has been reintroduced - https://main--shredit--stericycle.aem.live/en-us/secure-document-destruction-and-shredding-prices
![image](https://github.com/user-attachments/assets/2ef811c0-3da0-4482-bf19-bc35983d3af9)

Also I don't seem to have the ability to edit this page through Sidekick. Can you confirm what's going on here? 

![image](https://github.com/user-attachments/assets/1fc4b8e5-0a4c-4896-9472-0d4949dc2698)

**Comment by colinvlasak** [comment]
@MarquiseRosier @jindaliiita can you take a look a this one? It looks like the page is actually missing from EDS (which would explain why I can't edit it)? Can you ensure it is restored and look at the layout issue? 

https://main--shredit--stericycle.aem.live/en-us/secure-document-destruction-and-shredding-prices#get-a-quote

**Comment by jindaliiita** [comment]
@colinvlasak For me its visible
https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B694E065C-FF5A-4E72-AEA6-8E8182EB21BF%7D&file=secure-document-destruction-and-shredding-prices.docx&action=default&mobileredirect=true

**Comment by colinvlasak** [comment]
@jindaliiita thanks for confirming. 

The issue with the alignment still stands. Can you see that this is fixed?

![image](https://github.com/user-attachments/assets/59b4e1cb-8e35-47c0-89da-4b45935e1324)

**Comment by colinvlasak** [comment]
@jindaliiita how did you fix this? Is this something I could do in the future or was it a code adjustment?

**Comment by jindaliiita** [comment]
@colinvlasak It was a code adjustment. Somehow, the earlier changes were reverted, and the issue reappeared.

**Comment by colinvlasak** [comment]
@jindaliiita thanks for confirming
