### ISSUE TITLE
FAQ - Answers Bolded

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#345]
FAQ answers are bolded on pricing page. The answers in the acordion should not be bold, just the questions. This should apply to the component across the site.

https://main--shredit--stericycle.aem.page/en-us/secure-document-destruction-and-shredding-prices

![image](https://github.com/user-attachments/assets/b90a435d-7b85-4221-a3d0-c94e4e7b574c)

**Comment by MarquiseRosier** [comment]
Fixed!
