### ISSUE TITLE
Fragments within Components/Modals

### ISSUE THREAD

**Issue by rwcsrichardspencer** [aemsites/stericycle-shared#348]
@vdua @jalagari we'd like have the ability to put fragments & forms within columns and modals.
For example we have Columns table and in the 2nd column, we'd like to add a fragment and/or form.

**Comment by MarquiseRosier** [comment]
@ravise5 I believe this is where this capability is being tracked.

**Comment by ravise5** [comment]
@MarquiseRosier This is a duplicate of #514.  Also we have already added the support of fragments and forms in modals hence marking this as complete.
