### ISSUE TITLE
Modal Popups Functionality

### ISSUE THREAD

**Issue by rwcsrichardspencer** [aemsites/stericycle-shared#362]
We have the ability to do Modal Experience Fragments within AEM along with some options. These options include:

- Which Fragment to use/show in the modal
- ID (used for user initiated clicks to show modal)
- Lazy Load Modal Content
- Modal Size (Small, Medium, Large (default), Extra-Large)
- Trigger type (None - user click, Scroll Percentage, Page Time, Exit Intent)
- Scroll percentage value
- Page time (in seconds)
- Exit intent delay (in seconds)

See below screenshot with our current options/set up.

![modal](https://github.com/user-attachments/assets/a34b3bca-5e75-4aaa-80b3-5963579853b4)

It also needs to be able to connect with Adobe Analytics for tracking how many views, how many clicks, how many closes, etc...

**Comment by rwcsrichardspencer** [comment]
Some additional context:
Frequency
- Show once per visitor.
- Show on every visit.
- Show only on visit
- Show every visits.
- Don't show on first visit, show on all return visits

**Comment by rwcsrichardspencer** [comment]
@jindaliiita @jalagari @ravise5 where are we with the Modal functionality?

**Comment by ravise5** [comment]
@rwcsrichardspencer Can you review the URLs in the above PR in terms of functionality?
