### ISSUE TITLE
Forms - UTM Data

### ISSUE THREAD

**Issue by rwcsrichardspencer** [aemsites/stericycle-shared#364]
Wanting to ensure that UTMs for forms aren't just pulled from the URL, but also pulled from cookie data when no URL parameters are present as Google will sometimes cookie the user if they leave and return without the URL parameters. @ravise5 @jalagari

**Comment by ravise5** [comment]
@rwcsrichardspencer Yes we check the cookie, when url params are missing. 
https://github.com/aemsites/stericycle-shared/blob/main/blocks/form/utm.js#L28

Closing this issue.
