### ISSUE TITLE
Forms - Footer Newsletter Sign-up - Front End Rendering Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#386]
I just reviewed the "Get informed. Stay protected." form implementation in EDS on a few pages. I have some feedback regarding front styling/layout. See below.

1. The form is currently spanning the full width of the site. The form should be boxed to match the margins of the site
2. There is too much padding below the privacy policy and form input fields. Padding should be the same as the padding between between the text above.
3. Vertical padding top and bottom is not equal. They should be the same. The bottom is too small, The top looks right. Do we have a standard for padding between section that we can apply here?
4. Please add in a box shadow to divide the section from the content above 
5. Can you remove the duplicate "*" in the fields. There should only be one "*" after the label. e.g, First Name* - I realize it is like this on the live site but it's a legacy error not and intentional implementation. 

Example Page: https://main--shredit--stericycle.aem.live/en-us/who-we-serve/healthcare

![image](https://github.com/user-attachments/assets/02d2ff30-7d88-434a-a818-f3fca2f23d22)

![image](https://github.com/user-attachments/assets/4a03064b-8b5f-4b18-aa86-ea26e26d7041)

**Comment by colinvlasak** [comment]
@ravise5 @jalagari another ticket regarding form layout/rendering

**Comment by ravise5** [comment]
@colinvlasak the box shadow is not present across pages. Example URL: 
https://www.shredit.com/en-us/secure-shredding-services/residential-shredding-services

**Comment by colinvlasak** [comment]
@ravise5 we would like the box shadow to be present across pages as it keeps consistency across the site. On our current site we authored the footer newsletter form on a page by page basis. On pages where the section above is gray we did not include a box shadow, for pages where the section above is white we did include a box shadow to ensure separation. Adding a box shadow will ensure there is separation between the sections regardless of the section colour above.

**Comment by ravise5** [comment]
@colinvlasak Since this form embedding is controlled via regex in metadata,  to have a specific style for a specific page we would have to introduce a new attribute in metadata for this. We have already added too many metadata attributes at this point :) Would you prefer adding one more to control this? 
If you think thats okay I can go ahead with it.
cc: @jalagari

**Comment by colinvlasak** [comment]
@ravise5 can we have the style apply to all pages that the form is embedded on? It doesn't need to be page specific. Every instance of this form would have the box shadow. Then you could just apply the style to the form itself? Would that make it simpler?
