### ISSUE TITLE
Home Page - CTA Bar - Vertical Alignment Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#400]
CTA Bar on the home page is not properly aligned vertically. 

Text Phone number and CTA button should all be center aligned horizontally with equal padding top and bottom.

Link: https://main--shredit--stericycle.aem.live/en-us 

![image](https://github.com/user-attachments/assets/af4a6dde-6b5e-4858-9703-b629838055bf)

**Comment by kronnox** [comment]
I completely refactored the styling of the `Simple CTA` block and used it on the homepage to replace this section. You can find examples for all of the different styles in PR #449.
