### ISSUE TITLE
Home Page - Protecting your confidential information is our mission - Content Alignment

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#401]
Protecting your confidential information is our mission content should be centered not left aligned.

https://main--shredit--stericycle.aem.page/en-us

![image](https://github.com/user-attachments/assets/e92416cd-ae5f-43f1-8deb-8af3cce16121)

**Comment by kronnox** [comment]
FYI: The header can be centered by adding the `centered headings` style to the section styles. No code change required.

**Comment by colinvlasak** [comment]
@kronnox using center styling for the section fixed the headings but it makes the spacing a little bit off. Is there anything we can do to make the stats with blue bars look a bit cleaner? There's to much spacing between the blue bar and the text on the left. Want it to look more like live site. 

EDS
![image](https://github.com/user-attachments/assets/3878b0c8-68ed-4127-973f-1ecc2d0c9c22)

Live site
![image](https://github.com/user-attachments/assets/f1845a76-13d7-444e-9285-07788c569d81)

**Comment by kronnox** [comment]
You are right. That's not how it's supposed to look. The styles of the blue border thingys probably needs to be adjusted here, so they are not influenced by the `centered headings` section style; that's a bug.

**Comment by colinvlasak** [comment]
@bstopp @kronnox the spacing on the bars is fixed but the content needs be centered within the component

![image](https://github.com/user-attachments/assets/df0a4c5f-2c51-454a-863b-47d3cb7a9cc5)


Live

![image](https://github.com/user-attachments/assets/944bcf63-daec-4bcd-8903-f66a87aa253c)
