### ISSUE TITLE
Clickable Columns - Link Issue

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#416]
Clickable columns blocks links are going out to the old hlx site. Can you update to ensure the placeholder links are going to the main site?

https://main--shredit--stericycle.aem.page/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/clickable-columns&index=0

**Comment by colinvlasak** [comment]
@bstopp still seeing hlx links when I copy the component over to a document

![image](https://github.com/user-attachments/assets/3cdd128f-053f-47e6-acfd-89857e2e0416)

**Comment by bstopp** [comment]
The source content for all blocks provided in the Library can be found in Sharepoint under 
* Tools -> Sidekick -> Blocks

I updated this specific block to use the new URLs. Should it be used as the basis for future content.

**Comment by colinvlasak** [comment]
@bstopp thanks for the additional details on how the Library can be updated. I didn't realize it was document based as well. This is very helpful to know.

**Comment by bstopp** [comment]
Yep! i just asked Marquise to make sure this information made into the KT so that it's documented and available for future reference :)

**Comment by colinvlasak** [comment]
@bstopp awesome appreciate it! This is exactly the stuff we need to know so appreciate you flagging that for KT :)
