### ISSUE TITLE
FAQs - Body Text Rendering Too Small

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#419]
FAQ Body text appears to be rendering smaller than standard body text on the site. Please confirm how to fix this.

https://www.shredit.com/en-us/resource-center/faq

![image](https://github.com/user-attachments/assets/ace5247d-a05b-46c0-97b1-5b0ffaf0526a)

**Comment by MarquiseRosier** [comment]
looks like font-size is 1rem, line-height: 1.25rem all around; no matter the screen dimensions! Will make the adjustment in CSS
