### ISSUE TITLE
Tabs Block Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#441]
There are a few issues with the tabs block

**Tabs (vertical) - https://main--shredit--stericycle.aem.page/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/tabs&index=1**

1. Circle and text overlapping. Need more space between circles and text.

![image](https://github.com/user-attachments/assets/bc8d8323-ce65-4dca-81ba-4d8fb5c302cc)

Should look like:

![image](https://github.com/user-attachments/assets/9c0a70ee-e9cf-466b-a86b-8406d4bda68d)

2. Bullet issue is happening on tabs. Is there a way to fix sitewide? Seems to happen with all components and needs to be fixed idnividualy?

Example: https://main--shredit--stericycle.aem.page/en-us/test

![image](https://github.com/user-attachments/assets/b20f034a-72ec-40fc-90b4-ddb783c2d822)

On mobile bulleted text doesn't render at all

![image](https://github.com/user-attachments/assets/15f2430d-1660-4894-bd30-c160ce9e9333)

**Tabs (Video) - https://main--shredit--stericycle.aem.page/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/tabs&index=2**

3. Same issue with circle overlapping text

4. Block not rendering proper width. It's more narrow then rest of site. Should match width of standard site margins. 
5. There's a vertical scroll bar beside the video which should not be there

![image](https://github.com/user-attachments/assets/b623d882-58a8-4822-a5a5-0f49b845f5a8)

**Tabs (topics) - https://main--shredit--stericycle.aem.page/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/tabs&index=3**

6. image should link to same page as the text. See current live site for example - https://www.shredit.com/en-us/who-we-serve
7. Rendering when you copy over the component to a doc is a mess and doesn't really allow for proper authoring 

![image](https://github.com/user-attachments/assets/8d74c67e-70e8-46cc-8b9d-7cb6b364cc93)

8. Mobile rendering is poor. Should not have scroll bar. Should also stack 2 x 2 taking up full width of container
![image](https://github.com/user-attachments/assets/2765a356-8308-4726-9e2a-55daadb3d1a4)

**Comment by MarquiseRosier** [comment]
@colinvlasak the way that the block renders is we can tie a row of *cards to a tab title if the items are all in the same row. 
Doing it any other way would add developer complexity to the block; and the block is already pretty complex. My suggestion is to maybe not have content like this with multiple images and links in a tab like this aha it's already a bit unruly but if it's a must have we can talk about how we can rebuild this block.

**Comment by colinvlasak** [comment]
@MarquiseRosier which issue are you referring to in the comment above?

**Comment by bstopp** [comment]
Colin - i went out to [the test page](https://main--shredit--stericycle.aem.page/en-us/test) and I didn't see many of these issues outlined here. Is there any way to break them out into individual bugs? I'm not sure that they're all actually related to the `Tabs` block

**Comment by colinvlasak** [comment]
@bstopp it looks like @MarquiseRosier fixed most of the issues.

The ones that are still present are:

Tabs (topics) - https://main--shredit--stericycle.aem.page/tools/sidekick/library.html?plugin=blocks&path=/tools/sidekick/blocks/tabs&index=3

- image should link to same page as the text. See current live site for example - https://www.shredit.com/en-us/who-we-serve
- Rendering when you copy over the component to a doc is a mess and doesn't really allow for proper authoring image

![image](https://github.com/user-attachments/assets/a47ae067-527e-4120-a087-4b0a6952ce2a)

- Mobile rendering is poor. Should not have scroll bar. Should also stack 2 x 2 taking up full width of container image

![image](https://github.com/user-attachments/assets/014411eb-5422-4a5a-8155-e5d1f15b7889)

**Comment by bstopp** [comment]
Gotcha - let me see if can address these.

**Comment by bstopp** [comment]
Colin - I've opened PR to try to address both the UX and the Authoring considerations. Please take a look at the links referenced there. I've added you as a reviewer, so you should have seen a notification for it.

I've also added both of those Block Variations to the Library - they won't work on the default branch, but you should be able to use this:

https://feat-fetched-tabs--shredit--stericycle.aem.page/tools/sidekick/library.html?plugin=blocks
