### ISSUE TITLE
Search Results Missing Because of Missing Metadata

### ISSUE THREAD

**Issue by MarquiseRosier** [aemsites/stericycle-shared#450]
Some sites when imported do not contain required metadata like description, which is used to match results based on keyword searching. 

We have to figure out a way to get a relevant description text despite it not being in the meta elements in the head. 

@colinvlasak when these pages were imported, many of them were missing this data. Hence, why they don't contain the relevant column in the query-index. We will have to go back and update the documents we want to be searchable. 

@colinvlasak luckily; i can probably do this quickly via python script. My question is; which documents need this?

**Comment by rwcsrichardspencer** [comment]
@MarquiseRosier yes please. Not just this page description but also additional page data and general re-sync as well. Such as Page Properties: https://github.com/aemsites/stericycle-shared/issues/128

**Comment by jindaliiita** [comment]
Assigning to @MarquiseRosier as he is working on the fix for this.

**Comment by colinvlasak** [comment]
@MarquiseRosier I am still only seeing Blogs and resource center content in the search results. Our service pages, pricing page, local pages, etc. should all be appearing in search, above resource center results.

**Comment by MarquiseRosier** [comment]
@colinvlasak if you'd like please approve this PR :)
