### ISSUE TITLE
Asset Library Integration - PDF Support

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#452]
I was just testing adding download block content and trying to link to a PDF and ran into two issues.

1. it doesn't appear PDFs exist in the AEM Assets Library. Can you ensure that these are added and functioning as a filter type? We store all the PDFS on our DAM for the site. It looks to only support JPG, PNG and TIFF currently.

![image](https://github.com/user-attachments/assets/3c1433d1-9308-489e-949a-82e20bd9738f)

2. Once the PDFs are working how can we link the image and download button on he download block to the AEM Assets Library? With our current set-up in AEM we just include the reference to the PDF and it renders both the link and the preview of the image. Can we mirror this with EDS?

**Comment by jindaliiita** [comment]
@colinvlasak Can you please check https://www.aem.live/docs/aem-assets-sidekick-plugin#using-asset-references-for-pdf-zip-etc-when-authoring-content for the pdf part.

**Comment by colinvlasak** [comment]
@jindaliiita this doesn't really help. The problem is it appears that PDFs are not linked/accessible in our current AEM Assets library. The only file types I can select and search for are JPG, PNG, and TIFF. We need to get all of our PDFs in the DAM linked into the AEM Assets library and ensure they are accessible. We should have all file types that are currently in our DAM accessible and searchable through the AEM Assets library integration.

Current Set-up (only JPG, PNG, and TIFF)
![image](https://github.com/user-attachments/assets/1c6c17e6-c8d6-4bf4-810c-4a773cc9f2a9)

The article shows PDFs being supported

![image](https://github.com/user-attachments/assets/09e26f69-27bd-445b-8d58-2f1df5cebd91)

**Comment by colinvlasak** [comment]
@MarquiseRosier just realized SVGs are also missing. Please ensure they are added as well.

**Comment by MarquiseRosier** [comment]
@colinvlasak please check-in with @ericvangeem as I believe he's in charge of next steps for getting all of the media into the Assets Selector. I will close this as it's basically done on our end!
