### ISSUE TITLE
Contact Us - Not Rendering Properly

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#460]
The contact us page is not properly migrated/rendering. This is one of our key pages. 

https://main--shredit--stericycle.aem.page/en-us/contact-us

![image](https://github.com/user-attachments/assets/6cc0ce0e-9203-47d9-b3be-f77ef94c1cb9)

Should look like

https://www.shredit.com/en-us/contact-us

![image](https://github.com/user-attachments/assets/057941d1-c789-4bf5-b8c0-dd99cbb51078)

**Comment by ravise5** [comment]
@bstopp the form is already imported in this page, styling is yet to be merged.
I hope sites team would import the remaining blocks in the page.

**Comment by colinvlasak** [comment]
@MarquiseRosier looks like this is back to you. Can you get the rest of the page updated when you have a moment?

**Comment by colinvlasak** [comment]
@ravise5 there are some form styling issue with the contact us form on this page. See below.

EDS: https://main--shredit--stericycle.aem.page/en-us/contact-us
Live: https://www.shredit.com/en-us/contact-us

1) The Form doesn't appear to be respecting the page margins and doesn't align with the heading. Everything should be aligned left down the margin.  
2) The How quickly do you need your one time shredding service? should be removed. This field only applies if someone selects one time service and on our current site it doesn't work so just get rid of it.
3) Email Opt-in should be a checkbox not a radio button
4) Privacy policy should be the full text and the text should be smaller. It should also be below the submit button. 
5) Ensure clean vertical spacing between sections on the form. Current EDS version feels a bit crammed. See live example. 

![image](https://github.com/user-attachments/assets/5c6d7f1b-b56e-4aef-acff-5839b99568c2)

Should look like:

![image](https://github.com/user-attachments/assets/2502ffae-cd95-4b8f-98f6-146277f7b784)

**Comment by ravise5** [comment]
@colinvlasak please review https://get-a-quote--shredit--stericycle.aem.page/en-us/contact-us

**Comment by colinvlasak** [comment]
@ravise5 two issues here.

1. The margins appear to be a bit off. The image should stretch to the margin. And the accessibility statement and main copy should follow the same margin. 
2. There's too much vertical space after the Buy Online Button. Makes that whole boxed section visually unbalanced. The vertical padding below the button should be the same amount of vertical padding at the very top of the box. 

EDS
![image](https://github.com/user-attachments/assets/72c41a90-3a5b-47a7-aac0-396e766be75f)
![image](https://github.com/user-attachments/assets/f23bf766-a396-4ee7-b092-c0058359de14)


Live

![image](https://github.com/user-attachments/assets/6140d811-3962-45f2-a371-53d42537d40f)
