### ISSUE TITLE
Policies & Positions - Document Linking Broken

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#471]
The document links on the https://main--shredit--stericycle.aem.live/en-us/about/social-responsibility/policies-and-positions do not work. 

These links need to connect to the existing documents in the DAM. We reference these files across numerous pages and countries. The benefit of this set-up is we update the document once in the DAM and then all links pointing to it automatically connect to the new document. 

https://main--shredit--stericycle.aem.live/en-us/about/social-responsibility/policies-and-positions

**Comment by MarquiseRosier** [comment]
@colinvlasak I think this is something we will have to figure out

**Comment by colinvlasak** [comment]
@MarquiseRosier thanks for the update. This one is important so look forward to solving once the the functionality is available.
