### ISSUE TITLE
Columns (numeric list) - Mobile Rendering Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#488]
6 Step Security Protocol Not Rendering Properly - Overlapping text

Example: https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/specialty-shredding-service

![image](https://github.com/user-attachments/assets/85e244b6-a569-4f5b-ae40-41930b14be43)

**Comment by colinvlasak** [comment]
@MarquiseRosier there are still overlapping issues on mobile

![image](https://github.com/user-attachments/assets/32c40941-7b7f-4992-8237-e5b851b4d416)

**Comment by kronnox** [comment]
@MarquiseRosier I'm working on this. The whole column style is unnecessary. There has been a list style that actually fixes all of this from the very beginning. I just have to replace it on all the content pages and clean up the other styles.

**Comment by kronnox** [comment]
I identified 14 pages that use the old style:
https://main--shredit--stericycle.aem.page/en-us/email/regularly-scheduled-paper-shredding-with-shred-it-protectplus
https://main--shredit--stericycle.aem.page/en-us/marketing/bulk-paper-shredding
https://main--shredit--stericycle.aem.page/en-us/marketing/document-destruction-services-shred-it
https://main--shredit--stericycle.aem.page/en-us/marketing/hard-drive-destruction-service
https://main--shredit--stericycle.aem.page/en-us/marketing/new-paper-shredding-services
https://main--shredit--stericycle.aem.page/en-us/marketing/paper-shredding-service
https://main--shredit--stericycle.aem.page/en-us/marketing/shred-it-document-destruction
https://main--shredit--stericycle.aem.page/en-us/marketing/shred-it-document-destruction-inline
https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/specialty-shredding-service
https://main--shredit--stericycle.aem.page/en-us/email/tiered-shredding
https://main--shredit--stericycle.aem.page/en-us/offer
https://main--shredit--stericycle.aem.page/en-us/email/paper-shredding-services
https://main--shredit--stericycle.aem.page/en-us/email/offer
https://main--shredit--stericycle.aem.page/en-us/fragments/harddrive-destruction-service

**Comment by kronnox** [comment]
Turns out the exact style is actually only used here: https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/specialty-shredding-service

**Comment by kronnox** [comment]
@colinvlasak This should be resolved now. Since this is now default content styling rather than a block, I will have to figure out where to put the example in the block library. But I'll do so later

**Comment by colinvlasak** [comment]
@kronnox looks like this update broke the desktop styling

https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/specialty-shredding-service

![image](https://github.com/user-attachments/assets/5c05212f-610e-4970-b005-471702f06987)


Should be:

https://www.shredit.com/en-us/secure-shredding-services/specialty-shredding-service

![image](https://github.com/user-attachments/assets/99845beb-b72e-4a90-81de-dc8096b296cf)

**Comment by kronnox** [comment]
@colinvlasak I just forgot to click publish and only pushed it to `.page`, my bad

**Comment by colinvlasak** [comment]
@kronnox there we go!
