### ISSUE TITLE
Columns Bullet Alignment Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#490]
The bullet alignment is off when using columns vs. regular text. Creating margin issues. All margins should be consitent.

Example: https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/specialty-shredding-service

![image](https://github.com/user-attachments/assets/950e8c7d-2101-4503-a335-fd0161ffe1c1)

**Comment by kronnox** [comment]
This is actually a problem with the styling applied by the form. I'm referring this to the forms team, since I don't want to mess up their styles.

**Possible fix:**
The `.columns-wrapper` or rather or content divs in the `.two-column.form-container` need to be `width: 100%`.

**Comment by ravise5** [comment]
This issue is now fixed. Closing
