### ISSUE TITLE
Fragment - Why Choose Shred-it Rendering

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#493]
1. The Why Choose Shred-it Fragment should be rendering with the text aligned center but it is showing left aligned when rendered 

![image](https://github.com/user-attachments/assets/424ca46e-4010-449f-bb62-323856288605)

![image](https://github.com/user-attachments/assets/2aaca0fc-6d30-481e-a64d-1ac828e193e7)

2. Icons should also be larger (desktop & mobile)

Should match live site rendering

![image](https://github.com/user-attachments/assets/b7909955-3ecb-48d3-add9-261f0cb8ff27)

**Comment by kronnox** [comment]
@colinvlasak Where do I find this fragment?

**Comment by kronnox** [comment]
The first one is an easy fix on the authoring side: The `centered text` style on sections will only apply to default content within the section. For blocks you need to apply it to the block styles.

![Screenshot 2024-11-14 at 10 55 35](https://github.com/user-attachments/assets/9fc332b0-497d-47ad-bad7-4e1b1cab878c)
