### ISSUE TITLE
Desktop Margin Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#504]
Some sections on our service section of the site are not following the page margins. They are rendering full width vs boxed in the proper margins. This is new issue that just popped up today. I am wondering if this has to do with the page fixes on the SEM pages as they have different widths. 

Example: https://main--shredit--stericycle.aem.page/en-us/secure-shredding-services/one-off-shredding-service

![image](https://github.com/user-attachments/assets/61f1708d-5bbb-4ff0-8bca-c642f55f6e3f)

![image](https://github.com/user-attachments/assets/7b5d3ef6-9d05-4e4f-9316-605062648715)

**Comment by MarquiseRosier** [comment]
@colinvlasak yup that's on me; apologies, I made a sweeping margin change; that should be very easy to correct.

**Comment by MarquiseRosier** [comment]
@colinvlasak I think we should have a conversation about standardizing margins? I'm noticing that these are the only pages with this kind of different margin? Even within the marketing pages other pages don't really have this full screen styling?

**Comment by MarquiseRosier** [comment]
okay! Thanks @colinvlasak for the context : I'll be pushing the fix soon!)
