### ISSUE TITLE
marketing pages form embeds

### ISSUE THREAD

**Issue by MarquiseRosier** [aemsites/stericycle-shared#505]
@jalagari @ravise5 can you guys fix the rest of the forms embeds in the marketing section; the template marketing-location-page was meant to be a template; now it seems like you guys have figured out a way to embed the content without using that template, which has a significant LHS impact. Can you also change the rest of the marketing pages to do the same?

**Comment by ravise5** [comment]
@MarquiseRosier We have manually embedded these forms in lots of pages over the past few weeks, this would mean we have to redo all that. There are other pages also that use the marketing-location template other than `/marketing` pages.
cc: @jalagari

**Comment by ravise5** [comment]
I was checking the page-speed of https://main--stericycle-shared--aemsites.aem.page/en-us/marketing/locations/paper-shredding-columbus it doesn't seemed to be affected.
 https://pagespeed.web.dev/analysis/https-main--stericycle-shared--aemsites-aem-page-en-us-marketing-locations-paper-shredding-columbus/c1fyohlvo1?form_factor=mobile

Can you share a URL where this issue is reproducible?

**Comment by MarquiseRosier** [comment]
@jalagari @ravise5 okay that makes sense! I will say though; the styling on the two-columns forms in these two places are wrong. 

<img width="1711" alt="Screenshot 2024-11-14 at 9 26 50 PM" src="https://github.com/user-attachments/assets/7f4ee4d1-9fd3-4c5d-9f5a-e006ca3de66c">
<img width="1703" alt="Screenshot 2024-11-14 at 9 26 40 PM" src="https://github.com/user-attachments/assets/d042fc1a-418d-42d2-9d0e-5a209d29fcfe">

**Comment by MarquiseRosier** [comment]
@colinvlasak pointed this out here. #504

**Comment by MarquiseRosier** [comment]
@jalagari @ravise5 a better example is the first image should match the margin of the header. There should be alignment. 

<img width="1728" alt="Screenshot 2024-11-14 at 9 32 36 PM" src="https://github.com/user-attachments/assets/9bf82f0f-f83c-4d4a-90d0-d87f679a118b">


The second image should be aligned with the element above it. 
<img width="1728" alt="Screenshot 2024-11-14 at 9 32 49 PM" src="https://github.com/user-attachments/assets/298085e5-0811-4797-bd01-3cd90761a93e">

**Comment by ravise5** [comment]
@MarquiseRosier The fixed width for two column layout was for the scenario: https://github.com/aemsites/stericycle-shared/issues/504
Your change for this [page](https://main--shredit--stericycle.aem.page/en-us/marketing/bulk-paper-shredding) is correct, let me create a style separate class for this

**Comment by MarquiseRosier** [comment]
@ravise5 I wish haha because it's caused the following issue

https://main-change--shredit--stericycle.aem.page/en-us/secure-shredding-services/one-off-shredding-service

**Comment by colinvlasak** [comment]
@MarquiseRosier is looks like the margin is still off on these pages where the forms are. 

Example: https://main--shredit--stericycle.aem.live/en-us/marketing/bulk-paper-shredding?18

In the top portion it doesn't go out to where the button ends in the header. 

![image](https://github.com/user-attachments/assets/f23d90b6-f455-448b-95ab-3ac7f1f4057e)

In the bottom portion it goes beyond the button. Should be constrained to align with it. 

![image](https://github.com/user-attachments/assets/034f60c6-289a-40e9-91a9-93b30cec3013)

**Comment by colinvlasak** [comment]
@ravise5 top form is still not inline with the margin

![image](https://github.com/user-attachments/assets/21342dbc-1c1b-4832-8416-af47763173f6)

**Comment by ravise5** [comment]
Can invalidate cache and try once??

**Comment by colinvlasak** [comment]
@ravise5 cleared cache and opened in private browser but still seeing the margin issue on the top form on https://main--shredit--stericycle.aem.live/en-us/marketing/bulk-paper-shredding

**Comment by ravise5** [comment]
@colinvlasak Can you review this url: https://margins--shredit--stericycle.aem.live/en-us/marketing/bulk-paper-shredding

**Comment by colinvlasak** [comment]
@ravise5 that version looks good
