### ISSUE TITLE
Form - Design Issues - Industry Pages

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#516]
The form on the Industry pages is not rendering properly.

https://main--shredit--stericycle.aem.page/en-us/who-we-serve/healthcare

1. The Get A Quote heading is too small
3. The Fill out the form or call [877-542-3992] section is gray but the rest of the form is white. Whole form should be gray.
5. The  Fill out the form or call [877-542-3992] text is too big.

EDS:

![image](https://github.com/user-attachments/assets/8b6b4c70-bf4d-4f5a-b876-61fd6ac65f40)

Live:

![image](https://github.com/user-attachments/assets/9de2869c-e0e7-4b4a-8d4c-282a59f000c9)

There's also some weird rendering issue if scale down the screen size. Looks like tablet size. 

![image](https://github.com/user-attachments/assets/daed5405-f7b9-4157-83df-b2fc06f096a7)

**Comment by colinvlasak** [comment]
@ravise5 a few small issues with the vertical padding on this form

1) Get A Quote text - top and bottom vertical padding should be equal. Currently there is more at the bottom. 
2) Fill out the form text - top and bottom vertical padding should be equal. Currently there is more at the bottom. 
3) Select Service text is too close to the step image. should be more vertical space. Vertical space above and below Select Service should also be equal. 
4) Select Service text shouldn't be bold
5) All elements should be horizontally aligned


![image](https://github.com/user-attachments/assets/1d3f9d7b-918b-488b-9f36-e36b26e6f61f)

Should look like (all elements aligned upon single margin) 

![image](https://github.com/user-attachments/assets/12ace25e-fc02-45f3-89dc-285f1709d08b)

**Comment by ravise5** [comment]
@colinvlasak Can you review this url once before I merge the changes? 
https://get-a-quote--stericycle-shared--aemsites.aem.page/en-us/who-we-serve/healthcare

**Comment by ravise5** [comment]
Just want to reduce the to-and-fro here :-)
