### ISSUE TITLE
Hero Banner - Mobile Specific Imagery

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#527]
Discussed this on the Knowledge Transfer. We need to determine a solution to have a separate mobile image for the Hero banner. Ideally we could keep the functionality as it is if there is no mobile specific image uploaded. If mobile specific image is uploaded it would overwrite on mobile. 

cc: @kronnox @MarquiseRosier

**Comment by jindaliiita** [comment]
May be we can have something like this
https://main--sunstar--hlxsites.hlx.live/_drafts/satyam/section-with-background?view-doc-source=true

**Comment by MarquiseRosier** [comment]
@jindaliiita I assigned this to you; can you give some more explanation for @colinvlasak

**Comment by jindaliiita** [comment]
@colinvlasak
Could you please review the changes?

Pull Request: [GitHub PR #535](https://github.com/aemsites/stericycle-shared/pull/535)
Draft Preview: [Hero Block Changes](https://hero-block-changes--shredit--stericycle.aem.live/drafts/piyush/en-us)
Documentation: [Hero Block Specification](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B8E7BEDF7-93E2-471A-9BF2-1566CE1061B5%7D&file=en-us.docx&action=default&mobileredirect=true)

**Hero Block Behavior:**
**Two Images:**
The first image is used for mobile/tablet views.
The second image is used for desktop views.

**Single Image:**
If only one image is provided, the default flow will handle all views.

Let me know if you need further clarification.

**Comment by colinvlasak** [comment]
@jindaliiita looks good. 

Will this Hero block style be applied to all pages or something we would add manually to pages that need a separate mobile image? Will the autoblocking still exist?

**Comment by jindaliiita** [comment]
You need to manually add the images as specified below. For reference, you can check the [Hero Block Specification documentation](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B8E7BEDF7-93E2-471A-9BF2-1566CE1061B5%7D&file=en-us.docx&action=default&mobileredirect=true).

If you do not wish to add a mobile-specific image, the autoblocking feature will continue to function as usual.
