### ISSUE TITLE
Video Component - Stretching

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#531]
The video component appears to be stretching depending on the component it is placed in. On the home page its sctretching vertically. It should be the standard height the video is in, maintaining the aspect ratio. I have seen other instances where the video is stretched super wide to fill the space. The video should maintain the default aspect ratio and not stretch. 

![image](https://github.com/user-attachments/assets/b6f67313-a701-4268-8901-6a7c67873ca0)

**Comment by MarquiseRosier** [comment]
@colinvlasak can you approve https://github.com/aemsites/stericycle-shared/pull/534

That should about fix that
