### ISSUE TITLE
Forms - Modal - Single Step Styling Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#547]
There are some issues with modal form styling of the modal forms. This applies to all of the singe step variations (

1) X should be gray vs black
2) Fill out the form or call text should be normal size not small
3) Too much vertical space between form fields makes modal too long and doesn't fit on single screen. 
4) Request type should not be bold
5) Privacy Policy text should be small font style 
6) Reduce Vertical spacing between all section to make form more compact. See live form for guidance below.  

Left is EDS. Right Is Live. 
![image](https://github.com/user-attachments/assets/44465e56-9560-4928-ab04-f747ebd7b599)

**Comment by ravise5** [comment]
@colinvlasak Please review https://get-a-quote--shredit--stericycle.aem.page/en-us/marketing/bulk-paper-shredding

**Comment by colinvlasak** [comment]
@ravise5 looks much better!

3 small things to fix:
1) When an option is selected on the toggle button it should have a checkmark within it
2) The non-selected item should be centered horizontally within its button container
3) It appears there is extra padding around the form on EDS. Specifically on the right, bottom, and top. Can we make it uniform and reduced all around (see live example)?

Once the changes are applied please ensure they are made across all modal forms that have the same issues. 

EDS
![image](https://github.com/user-attachments/assets/b663585e-fa09-4d34-a7f2-cd56b6a07ef8)

Live:
![image](https://github.com/user-attachments/assets/a44a147f-844c-4304-86f4-76b217b95333)

**Comment by colinvlasak** [comment]
@ravise5 looks much better. One final thing. The spacing between the intro text and the first form field is still is too big. Should be same amount of spacing as between the form title and intro text.

Example: https://main--shredit--stericycle.aem.page/en-us/marketing/shred-it-document-destruction-inline

![image](https://github.com/user-attachments/assets/7b4558d8-4659-4835-bf34-4e1937c6433b)
