### ISSUE TITLE
National Accounts - Header - Wrong Colour

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#554]
The header for our National Accounts pages in EDS is incorrect. It should be navy blue but is primary blue. This applies to all pages in /national-accounts

Example:
https://main--shredit--stericycle.aem.page/en-us/national-accounts/una
https://www.shredit.com/en-us/national-accounts/una

**Comment by kronnox** [comment]
Maybe it was already fixed

**Comment by colinvlasak** [comment]
@kronnox looks good!

**Comment by colinvlasak** [comment]
@kronnox how did you update this and what is the best way to control it?
