### ISSUE TITLE
Form Styling - National Accounts

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#555]
Form styling is not rendering properly on https://main--shredit--stericycle.aem.page/en-us/national-accounts/una.
1) The Form heading is rendering too small.
2) The vertical padding in the top and bottom sections is uneven. Too much space after Get A Quote. Not enough after the field and the email opt-in. Too much after the privacy policy.

I have logged similar issues for other forms in separate tickets. Can we see that these issues are fixes across all forms? 

EDS

![image](https://github.com/user-attachments/assets/9090b60e-5cac-4806-b462-48c987ade80c)

Should look like:

https://www.shredit.com/en-us/national-accounts/una

![image](https://github.com/user-attachments/assets/91a6cab8-6a93-4a50-b3eb-d77761c9c7df)

**Comment by ravise5** [comment]
@colinvlasak common fixes from other issues will be carried over here the PR merge is pending that's why. 
We have decided to go with a standard width for the forms across sites as discussed in a previous call

**Comment by ravise5** [comment]
Removed email opt-in. as it not in actual form

**Comment by colinvlasak** [comment]
@ravise5 the heading size is fixed but the vertical padding still needs to be fixed. The vertical padding should be consistent. We seem to have the same issues across multiple forms where there is too much padding between title or description and the form fields. And between the button and the privacy policy text. 

Link: 
![image](https://github.com/user-attachments/assets/c1a8dd74-1451-4f74-a648-926256e35909)

![image](https://github.com/user-attachments/assets/cce2ac9c-41b0-4f46-aaa7-0d4384011f31)

See vertical spacing on live:
![image](https://github.com/user-attachments/assets/a8e83275-927d-418d-b559-bd5af763cd0d)
