### ISSUE TITLE
New SEM Page - Nav Links Not Working

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#556]
The nav links are not working on the new SEM pages. This applies to all versions using the header which has the nav links within it. Please fix all.

Example:

https://main--shredit--stericycle.aem.page/en-us/marketing/shred-it-document-destruction-inline

Should work like:

https://www.shredit.com/en-us/marketing/shred-it-document-destruction-inline#who-we-are

**Comment by colinvlasak** [comment]
@kronnox the links themselves weren't working. Nothing happened when you clicked on them before. Seem to be fixed now. 

How do we set anchors on the pages to ensure this works for other pages? Can we change the link titles on each page? I noticed on https://main--shredit--stericycle.aem.live/en-us/marketing/bulk-paper-shredding - the services link isn't really relevant. It should be "How It Works" linking to Customize Your One-Time Bulk Shredding Service section.

**Comment by jindaliiita** [comment]
@colinvlasak No, you cannot change the link on each page as it is related to the header.
I doubt there is a way to handle this use case in EDS.
The only solution I know is to create an alternate header (alt-nav) and include it on the specific page.
@kronnox Let me know your thoughts on this.

**Comment by jindaliiita** [comment]
@colinvlasak, please let me know if the above approach works for you. I can add three fields in the metadata to set the links for the three anchor tags in the header.

**Comment by colinvlasak** [comment]
@jindaliiita I think that should work. Would the metadata be just the link itself or the text as well?

**Comment by colinvlasak** [comment]
@ravise5 okay thanks. Let's go with the solution to have the links and form in metadata. If I need to change the text I can create a variant of the header as suggested.
