### ISSUE TITLE
New SEM Pages - Header/Footer Get A Quote

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#557]
The Get  A Quote button on the new SEM pages header and footer is incorrect. It currently launches the generic multistep form used across the site. These new SEM pages that use this template should be mapped to the form that applies to the page. On the inline form page it should be  https://main--shredit--stericycle.aem.page/forms/landing-page-modal. Part of the challenge is we use different forms on different pages. In our current set-up the header and footer are authorable elements within each page to allow this flexibility. 

This only applies to the marketing pages that have the new template (navy blue header with links, wider margins).

Example:
https://main--shredit--stericycle.aem.page/en-us/marketing/shred-it-document-destruction-inline

Should match:
https://www.shredit.com/en-us/marketing/shred-it-document-destruction-inline#who-we-are

**Comment by ravise5** [comment]
@colinvlasak seems like the form path was hardcoded via code for the nav you are referring to. Which shouldn't be the case. Let me check this with the team.

**Comment by colinvlasak** [comment]
@ravise5 sounds good keep me posted. In our current CMS the button is editable on a page by page basis. The entire header is authorable per page. Not sure if this is the best option but the CTA button and page links need to be able to differ from page to page using this layout/template.

**Comment by colinvlasak** [comment]
@ravise5 noticed a second GAQ was added. May just be work in progress but wanted to flag. Also the phone number in these headers is incorrect. It should match the phone number in the footer and form - 877-542-3992

https://main--shredit--stericycle.aem.page/en-us/marketing/shred-it-document-destruction-inline

![image](https://github.com/user-attachments/assets/268d57e3-0681-47d5-a607-34efeb5907c5)

**Comment by ravise5** [comment]
@colinvlasak Yeah there might be issue in nav and footer modal buttons untill the above PR is merged. Please ignore.

**Comment by ravise5** [comment]
@colinvlasak now you can configure modals via metadata sheet. I have introduced 2 new columns `nav-modal-path` and `footer-modal-path` , I have added the entry for the above page. You can configure for the rest.

**Comment by colinvlasak** [comment]
@ravise5 the footer Get A Quote button is not showing on the page.

![image](https://github.com/user-attachments/assets/6692baa5-959d-420a-b4ca-807a14b3f963)

I tried adding footer-modal-path to the metadata but it doesn't seem to do anything. Is this done correctly?

![image](https://github.com/user-attachments/assets/6277ba31-4f8a-4bb2-a91f-da58a960d502)

**Comment by ravise5** [comment]
@colinvlasak seems like a bug let me check

**Comment by ravise5** [comment]
@colinvlasak Can you check now?

**Comment by colinvlasak** [comment]
@ravise5 the button is now showing in the footer but when I click it, it goes to a seperate page with the form instead of launching the modal. Is that an issue with the button itself or an authoring issues on my end?

![image](https://github.com/user-attachments/assets/3874f7a0-4ff8-491d-a56c-d4f300d7e330)

**Comment by ravise5** [comment]
@colinvlasak its your url should have `/modals/` in the path only then it opens as a modal. 
You can place this page inside `/forms/modals` folder and test again

**Comment by colinvlasak** [comment]
@ravise5 thanks. I added /modals/ to the url and it is rendering properly. 

For the button copy "Request A Free Quote" is this authorable for the footer? Want to simplify it to "Request A Quote". If I can do it on my end, I am happy to.

**Comment by ravise5** [comment]
Yes you can specific it in the placeholder sheet for en-us. 
https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7B2C39A222-CD5E-494F-8775-EE44E6FB21B8%7D&file=placeholders.xlsx&action=default&mobileredirect=true

Just change the Text column value against  key`requestAFreeQuote`,

**Comment by colinvlasak** [comment]
Got it thank you!

One last thing I am seeing two CTA buttons in the footer on some pages

Example: https://main--shredit--stericycle.aem.live/en-us/secure-shredding-services/one-off-shredding-service

![image](https://github.com/user-attachments/assets/27a0149d-c7e9-448a-9705-e600e6995e9e)

I am assuming this is related to this. Can you take a look?

**Comment by ravise5** [comment]
This happened because I forgot to publish the footer doc after change, now it should be fixed. 
Can you clear cache and test once and close this issue once done?

**Comment by colinvlasak** [comment]
@ravise5 looks good now
