### ISSUE TITLE
New SEM Page - Mobile Layout Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#558]
There are some issues with the mobile rendering on the new SEM pages. 

Example: https://main--shredit--stericycle.aem.page/en-us/marketing/shred-it-document-destruction-inline

1) The margins are off 
2) The Secure, Customizable, Cost Effective section should appear below the form on mobile
3) First Name and Last Name should be on a separate line for mobile. If this is difficult to achieve can we just update the form to have them on separate lines on desktop as well?
4) The icons are rendering too small

![image](https://github.com/user-attachments/assets/bc07584c-3c94-4652-b464-1bd8d25edc59))

![image](https://github.com/user-attachments/assets/dbf332f3-bd70-4e2f-bf69-c3661c9309cc)

![image](https://github.com/user-attachments/assets/d8d45351-1f23-4079-92a0-e87c32060659)

**Comment by MarquiseRosier** [comment]
Hey @ravise5 @jalagari this is forms.css not respecting margins. can you start the PR i'll jump in and fix the icon size. But this is the grid display setup on this page.

**Comment by ravise5** [comment]
@MarquiseRosier Here you go! 
Now since the column wrapper with icons are pushed below the form, you would need to adjust the background image accordingly in mobile layout.

**Comment by colinvlasak** [comment]
@MarquiseRosier would prefer to keep background image on mobile if possible. Want to align to current live site if we can.
