### ISSUE TITLE
Multistep Form - Logic Issue

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#560]
The multistep from is displaying "How quickly do you need your one time shredding service?" on step 4. Regardless of the service selected on step one. This question should only appear if the user selects one time shredding service. Please ensure this is fixed across all variation of the multistep form (modal, inline, campaign, etc.)

![image](https://github.com/user-attachments/assets/e994c593-be18-47c0-ad95-9d396dcfbe95)

Example page: https://main--shredit--stericycle.aem.live/en-us (click Get A Quote in header)

**Comment by ravise5** [comment]
@colinvlasak 
![image](https://github.com/user-attachments/assets/daa36050-2ba0-4489-a9f2-a63e0570e5ef)
`One time shredding service` and  `Hard drive destruction` has the same value "Purge" is this correct?
We use input values to hide and show, so the rule will execute for both the options.

**Comment by colinvlasak** [comment]
@ravise5 the way it is mapped on our current site it is directly dependent on the servicetyp1 based on name not the value.

Example form: https://author-p29452-e94470.adobeaemcloud.com/ui#/aem/aem/experience-fragments.html/content/experience-fragments/shred-it/us/en/site/multistep-inline-form

![image](https://github.com/user-attachments/assets/e16b0f94-885f-4382-8dd2-6ceb5bf77c79)

![image](https://github.com/user-attachments/assets/72789749-ab21-4fe1-b5f8-37d7ddec91dd)

Technically for the value both pass through as purge but one time flags the service as paper while hard drive flags as hard drive.

![image](https://github.com/user-attachments/assets/9ea34102-a60d-474f-a33e-b25d640181c2)

The "How quickly do you need your one time shredding service?" on step 4 should only apply to users who select the One-time shredding option

@rwcsrichardspencer may have more details on how this works.

**Comment by ravise5** [comment]
@colinvlasak This is now done for all forms

**Comment by colinvlasak** [comment]
@ravise5 looks good!
