### ISSUE TITLE
Mobile - SEM Pages - Form Rendering Issue

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#561]
The /forms/campaign-variants/get-a-quote-campaign.json  form is not rendering properly on mobile. This is happening on all pages that use this form. 

Example: https://www.shredit.com/en-us/marketing/23purge

![image](https://github.com/user-attachments/assets/ee68cb72-093e-4f6b-bfc1-a8301b50e45c)

**Comment by ravise5** [comment]
This issue is now fixed. via: https://github.com/aemsites/stericycle-shared/pull/552

**Comment by colinvlasak** [comment]
@ravise5 rendering issue flagged previously however it is now rendering too narrow. can we see that it spans the full width of the mobile margins?

EDS

![image](https://github.com/user-attachments/assets/e980a254-2410-4c27-9647-e7c10deaa59d)

Live:
![image](https://github.com/user-attachments/assets/2278370c-6c14-4535-bd82-1167c297d277)
