### ISSUE TITLE
Legacy SEM Pages - Bottom Content Full Width

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#565]
Why Shred-it section and T&Cs should be full width (to page margins). Currently look be like 8 columns. 

https://main--shredit--stericycle.aem.live/en-us/marketing/paper-shredding-services-shred-it
https://main--shredit--stericycle.aem.live/en-us/marketing/document-destruction-service-shred-it 
https://main--shredit--stericycle.aem.live/en-us/marketing/mobile-shredding-for-one-time-and-regular 
https://main--shredit--stericycle.aem.live/en-us/marketing/paper-shredding-services-shred-it

**Comment by jindaliiita** [comment]
Authoring issue, now seems to be fixed

**Comment by colinvlasak** [comment]
@jindaliiita awesome, thanks!
