### ISSUE TITLE
Press Room Issue - Invalid Date

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#570]
The press room page is not rendering properly. This is a new issue as it was working fine before. It says Invalid date - https://main--shredit--stericycle.aem.page/en-us/about/press-releases 

![image](https://github.com/user-attachments/assets/e6174fd2-4e55-48ec-8597-e2082a972f4e)

**Comment by jindaliiita** [comment]
@colinvlasak Its not reproducible. Can you please check again.
