### ISSUE TITLE
Who We Serve - Tabs Not Rendering

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#587]
The tabs section that sends users to the individual pages on the who we serve section is not rendering. This was working until recently.

https://main--shredit--stericycle.aem.live/en-us/who-we-serve

EDS
![image](https://github.com/user-attachments/assets/0a364665-5a31-4a3c-a017-a16d2def8256)

Live
![image](https://github.com/user-attachments/assets/51022758-5be1-42c5-9d42-79cff6cc9180)

@MarquiseRosier @bstopp

**Comment by MarquiseRosier** [comment]
fixed! Just had to publish :)
