### ISSUE TITLE
Request Quote Modal - Duplicate Description

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#590]
The form description is duplicated on: https://main--shredit--stericycle.aem.page/forms/modals/request-quote

![image](https://github.com/user-attachments/assets/ce3d77a6-480a-4102-8d3c-d54b9dc759fc)

**Comment by ravise5** [comment]
This happened because there is a fragment in the form and the decription is present in the doc as well.
I've fixed it in the doc

**Comment by colinvlasak** [comment]
@ravise5 thanks for confirming and fixing. Will keep in mind for future occurrences
