### ISSUE TITLE
Data Protection Report - Gated Download Not Working

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#605]
The gated download on https://main--shredit--stericycle.aem.live/en-us/data-protection-report does not work.

When you enter your details into the form, the form should update with a download button and image of the report.

EDS: https://main--shredit--stericycle.aem.live/en-us/data-protection-report
Live: https://www.shredit.com/en-us/data-protection-report

This is what happens now:

![image](https://github.com/user-attachments/assets/44c785e3-69f4-46a6-9359-0e89771bd151)

This is what should happen:

![image](https://github.com/user-attachments/assets/1b71becb-a87c-488e-a785-28a1fd40f88a)

**Comment by colinvlasak** [comment]
@ravise5 I am still seeing a submission error when I try to submit the form

![image](https://github.com/user-attachments/assets/0e024fd5-7ef4-406d-b14d-917c75411e23)

**Comment by ravise5** [comment]
@colinvlasak Please test the form submissions the stage url, in this case 
https://stage-us.shredit.com/en-us/data-protection-report

**Comment by colinvlasak** [comment]
@ravise5 works on stage. Will it work on https://main--shredit--stericycle.aem.live/ as well?

**Comment by ravise5** [comment]
No you would have to use some cors plugin for now.

**Comment by colinvlasak** [comment]
@ravise5 thanks for confirming
