### ISSUE TITLE
Add dataLayer integration to blocks and forms

### ISSUE THREAD

**Issue by kronnox** [aemsites/stericycle-shared#608]
The dataLayer integrations (https://herodigital.slack.com/files/U05NT8ZRPU1/F083VHC0JPM/stericycle-datalayer-aem-code.zip) need to be manually added to the corresponding new blocks and forms.

- [x] Global Analytics Tracking
- [ ] Remaining blocks:
  - [ ] EventFinder ?
  - [x] Search Locations
  - [x] Search Site (#631)
- [x] Remaining forms items:
  - [x] Modals
  - [x] Embed ?
  - [x] XF Modals
  - [x] Info Modal
  - [x] Form Container

Part of #365

**Comment by kronnox** [comment]
My working branch is `issue/608/blocks`. Feel free to work in that as well as it has the `sendDigitalDataEvent` method to send events to the `digitalData` layer.

**Comment by ravise5** [comment]
Forms analytics events are added to the mentioned branch
