### ISSUE TITLE
Missing Page - Welcome

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#610]
https://main--shredit--stericycle.aem.live/en-us/welcome does not work. It currently shows an error saying:

"This page isn’t working
main--shredit--stericycle.aem.live redirected you too many times.
[Try deleting your cookies](https://support.google.com/chrome?p=rl_error&hl=en-US).
ERR_TOO_MANY_REDIRECTS"

This is a page used for customer onboarding

It should match the live site - https://www.shredit.com/en-us/customer/welcome

**Comment by jindaliiita** [comment]
Wrong redirection was present in the redirects. Now fixed

**Comment by jindaliiita** [comment]
@colinvlasak If you find any design issues in this page. you can open new issues for them.

**Comment by colinvlasak** [comment]
@jindaliiita logged two small issues re design/rendering here: https://github.com/aemsites/stericycle-shared/issues/662
