### ISSUE TITLE
Modal Pop-up Form - Padding Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#614]
There are some padding issues with mobile pop-up form. The text does not have proper vertical padding. Should match with the bottom.

![image](https://github.com/user-attachments/assets/fe406cb5-3172-4845-8a0c-83ba0d11c243)

Example: https://main--shredit--stericycle.aem.page/en-us/marketing/locations/paper-shredding-columbus

**Comment by ravise5** [comment]
This is now done

**Comment by ravise5** [comment]
The modal was not published thats the issue it should be fixed now
