### ISSUE TITLE
Image-Based Modal Pop-up Issues 

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#615]
I am trying to create an image based modal in EDS and ran into two issues. 

This is something we leverage on our live site. You can see an example on any local pages: https://www.shredit.com/en-us/service-locations/omaha (Wait 5 seconds)

**Issues**

1) I created the fragment for it in modals and added in an image - https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/Shared%20Documents/sites/shredit/forms/modals/[Document.docx](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/Shared%20Documents/sites/shredit/forms/modals/Document.docx?d=w6cb317a2d0f840ddba25451cb11334dd&csf=1&web=1&e=BGa0Xi)?d=w6cb317a2d0f840ddba25451cb11334dd&csf=1&web=1&e=BGa0Xi

I can't figure out to add a hyperlink to the image. It should link to https://main--shredit--stericycle.aem.live/en-us/offer?popup

2) I tried applying the modal to all the locations pages using the metadata spreadsheet but it doesn't seem to work.

https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BA3033076-B491-4BA2-93A2-FE2AD8853981%7D&file=metadata.xlsx&action=default&mobileredirect=true

![image](https://github.com/user-attachments/assets/6686b30f-5160-4304-9bbd-ddecb9965f7a)

**Comment by ravise5** [comment]
@colinvlasak please check this link: https://margins--shredit--stericycle.aem.page/en-us/service-locations/omaha

In this URL I have added it in the page metadata, but it should work with metadata sheet as well, when you do via metadata sheet I have observed it takes some time to reflect across all the regex pages. 

Refer this image [document](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/Shared%20Documents/sites/shredit/forms/modals/image-limited-time-offer.docx?d=w6cb317a2d0f840ddba25451cb11334dd&csf=1&web=1&e=LbJrqb)https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/Shared%20Documents/sites/shredit/forms/modals/[image-limited-time-offer.docx](https://adobe.sharepoint.com/:w:/r/sites/HelixProjects/Shared%20Documents/sites/shredit/forms/modals/image-limited-time-offer.docx?d=w6cb317a2d0f840ddba25451cb11334dd&csf=1&web=1&e=LbJrqb)?d=w6cb317a2d0f840ddba25451cb11334dd&csf=1&web=1&e=LbJrqb

In section metadata you will have to add the following:
![image](https://github.com/user-attachments/assets/6dc61ddd-683b-41d6-b951-4983a4f863dd)

Where link is the relative redirect URL.

This change is yet to be merged into main

**Comment by colinvlasak** [comment]
@ravise5 this works! let me know when merged to main and we can test adding it to all local pages using the metadata sheet

One note I noticed that on all the pop-ups including this one the x has a sqaure box around it on load. Can you ensure that is removed? Should apply to all pop-ups including pop-up forms/modals

![image](https://github.com/user-attachments/assets/43f951f8-32c4-4b81-b64d-5a57301c5c27)

**Comment by colinvlasak** [comment]
@ravise5 I tried adding this to the live site via meta-data but it's not showing on the local pages. Is there something I am missing here?

![image](https://github.com/user-attachments/assets/2760a5a9-f86f-4528-aa12-bd0801ee2a62)


https://adobe.sharepoint.com/:x:/r/sites/HelixProjects/_layouts/15/Doc.aspx?sourcedoc=%7BA3033076-B491-4BA2-93A2-FE2AD8853981%7D&file=metadata.xlsx&action=default&mobileredirect=true

**Comment by ravise5** [comment]
@colinvlasak The regex is wrong it should be `/en-us/service-locations` for now I have updated the same in sheet.

**Comment by ravise5** [comment]
I can see its now working fine across location pages:
https://main--stericycle-shared--aemsites.aem.page/en-us/service-locations/omaha

**Comment by colinvlasak** [comment]
@ravise5 thanks for confirming and the help on this! Will keep proper regex in mind for future additions.
