### ISSUE TITLE
Breadcrumbs Issues - About Pages

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#621]
@MarquiseRosier a new issue just appeared on this page - https://main--shredit--stericycle.aem.live/en-us/about/careers/our-culture

There's some weird breadcrumbs being added and it's not styled properly. Can you see that this entire white breadcrumb section is removed. I don't see it in the document to delete it.

This seems to happening across our all of our about pages. A few examples:

https://main--shredit--stericycle.aem.live/en-us/about/news-articles
https://main--shredit--stericycle.aem.live/en-us/about/press-releases
https://main--shredit--stericycle.aem.live/en-us/about/social-responsibility/diversity-inclusion

![image](https://github.com/user-attachments/assets/6124c06e-a39a-45f6-b682-10f715c247c8)

**Comment by jindaliiita** [comment]
@colinvlasak Its somehow not reproducible for me.

**Comment by colinvlasak** [comment]
@jindaliiita looks like it is fixed!
