### ISSUE TITLE
Additional Page Properties

### ISSUE THREAD

**Issue by kronnox** [aemsites/stericycle-shared#629]
Have we accounted for the Page Properties that are on each page? These properties connect to both the forms and datalayers. How can we get these imported?
![page-properties](https://github.com/user-attachments/assets/1e0bb47b-a35b-4cd1-b4be-41d2a14212f0)

_Originally posted by @rwcsrichardspencer in https://github.com/aemsites/stericycle-shared/issues/128#issuecomment-2444501446_

**Comment by rwcsrichardspencer** [comment]
@kronnox this was mentioned in this ticket back in October: https://github.com/aemsites/stericycle-shared/issues/128
Yes we need these page properties and we discussed using a metadata spreadsheet to accomplish this.

**Comment by kronnox** [comment]
Page properties can be configured in the `page-properties` spreadsheet. I copied over the spreadsheet that was provided to me and replaced all entries that had the parent page note with one for the page itself and one for all sub-pages (/** suffix). E.g.:
`/en-us/about/news-articles` was copied over to a second row for `/en-us/about/news-articles/**`.

**Comment by kronnox** [comment]
I think there are still a bunch of paths in there that can probably be generalized by `paren pages` ie. the service location pages. I'm leaving that to the Stericycle team as I don't want to break your current setup
