### ISSUE TITLE
Hard Drive - Legacy SEM - Spacing Issues

### ISSUE THREAD

**Issue by colinvlasak** [aemsites/stericycle-shared#647]
The spacing is off between the title and content section on https://main--shredit--stericycle.aem.page/en-us/marketing/protect-your-business-shred-it-hard-drive-destruction

I tried getting rid of the page section break between the title and the content but it destroys the page rendering if removed. How can we fix this?

https://main--shredit--stericycle.aem.page/en-us/marketing/protect-your-business-shred-it-hard-drive-destruction

![image](https://github.com/user-attachments/assets/652c759b-d1e5-4416-8f54-9cc985bbf001)

**Comment by MarquiseRosier** [comment]
Hey @ravise5 @jalagari this involves the display: grid stuff you've done here! I think maybe your grid stuff might not be able to accomodate more than 3 elements? Title, Body, and then Form, but there's a 4th element in the section. 

This is absolutely a forms thing as you folks created the css for two-columns, sidebar-left.

**Comment by colinvlasak** [comment]
@ravise5 I think this should work from my side. Can we push this to the live site?

**Comment by ravise5** [comment]
Changes are merged this should now be fixed @colinvlasak

**Comment by colinvlasak** [comment]
@ravise5 looks good!
