### ISSUE TITLE
Header - menu closes too soon

### ISSUE THREAD

**Issue by seanathero** [aemsites/stericycle-shared#86]
On desktop, when hovering over a Header link, the menu opens, but closes too soon for a user to reach it.
![Screenshot 2024-08-01 at 9 28 40 AM](https://github.com/user-attachments/assets/214517fa-434a-4e29-8ed8-03e08401fb7f)

**Comment by MarquiseRosier** [comment]
we investigated this on a call earlier; and it's because there's a focus event listener; so as soon as the mouse leaves; any action triggered by that event listener will cease. So the dialogue closes!

should be fixed with an onHover
