### ISSUE TITLE
Header - Language menu open unrelated content

### ISSUE THREAD

**Issue by seanathero** [aemsites/stericycle-shared#87]
On desktop, opening the language menu displays unrelated content
![Screenshot 2024-08-01 at 9 28 33 AM](https://github.com/user-attachments/assets/50e7f8d4-77b5-4c5b-8751-6ec0adc3e905)

**Comment by MarquiseRosier** [comment]
@dkuntze should this even be a thing; since we're only porting over en-us pages?

**Comment by jindaliiita** [comment]
Handled via https://github.com/aemsites/stericycle-shared/pull/96

**Comment by jindaliiita** [comment]
Closing this as it is handled via https://github.com/aemsites/stericycle-shared/pull/96
